### ISSUE TITLE
Boss fights...a LOOOOT of them....

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#10]
Anyone seeing a crazy amount of boss attacks in the ActionLog lately? Seems to only happen with the "Supers"
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/3414886/ActionLog.txt)

Even the ErrorLog is like "WTF?"
6/29/2019 6:24:10 PM
	Error Cloud Script Error: send WB {"ok":false,"err":"Maximum 2 attacks"}
6/29/2019 6:29:08 PM
6/29/2019 6:29:10 PM
	Error Cloud Script Error: send WB {"ok":false,"err":"Maximum 2 attacks"}
6/29/2019 6:34:12 PM
6/29/2019 6:34:15 PM
	Error Cloud Script Error: send WB {"ok":false,"err":"Maximum 2 attacks"}

Working fine, as far as I can tell with the regular bosses

**Comment by MatthieuBonne** [comment]
Did you put more than 2 in the "attack target" box for Super bosses ?

**Comment by Vitae666** [comment]
Not home right now to check. Pretty sure I put 2 on all of them. Unless it reset for some reason.

**Comment by MatthieuBonne** [comment]
Ok ! I'm also adding a 5sec delay between wb attacks in the next version, just in case...

**Comment by Vitae666** [comment]
![image](https://user-images.githubusercontent.com/9310914/61831190-17604780-ae3b-11e9-8787-3e11fa8f1ba8.png)

**Comment by MatthieuBonne** [comment]
No bug then, automater keeps trying a 3rd attack. Maybe we should hard-block supers at 2 ?

**Comment by Vitae666** [comment]
So are 2 the max # of hits? Don't remember reading that, but knowing me, I did and forgot 😁

**Comment by Vitae666** [comment]
Still happening on latest version :(

ActionLog.txt
7/26/2019 9:28:47 PM
	SUPER LORD OF CHAOS No Heroes fought with: A1 A1 A1 W29 W25 W30
7/26/2019 9:33:49 PM
	SUPER LORD OF CHAOS No Heroes fought with: A1 A1 A1 W29 W25 W30
7/26/2019 9:38:50 PM
	SUPER LORD OF CHAOS No Heroes fought with: A1 A1 A1 W29 W25 W30

ErrorLog.txt
7/26/2019 9:28:47 PM
7/26/2019 9:28:50 PM
	Error Cloud Script Error: send WB {"ok":false,"err":"Maximum 2 attacks"}
7/26/2019 9:33:49 PM
7/26/2019 9:33:51 PM
	Error Cloud Script Error: send WB {"ok":false,"err":"Maximum 2 attacks"}
7/26/2019 9:38:50 PM
7/26/2019 9:38:52 PM
	Error Cloud Script Error: send WB {"ok":false,"err":"Maximum 2 attacks"}

Not sure what that blank line is in ErrorLog.txt but that happens a looot

**Comment by MatthieuBonne** [comment]
Fine, I hard block to 2, it'll be in the next commit.

**Comment by MatthieuBonne** [comment]
Commit pushed.

**Comment by Vitae666** [comment]
Should it still display more than 2 and be able to change to more than 2?
![image](https://user-images.githubusercontent.com/9310914/62343087-5c2d5380-b4b7-11e9-8d42-a51f245ed415.png)

**Comment by Vitae666** [comment]
9/15/2019 11:09:19 AM
	SUPER LORD OF CHAOS Heroes Allowed fought with: athert:99 thert:99 aurora:19 raiderrose:99 W31 ageum:99
9/15/2019 11:09:22 AM
	SUPER LORD OF CHAOS Heroes Allowed fought with: athert:99 thert:99 aurora:19 raiderrose:99 W31 ageum:99
9/15/2019 11:10:16 AM
	SUPER LORD OF CHAOS Heroes Allowed fought with: athert:99 thert:99 aurora:19 raiderrose:99 W31 ageum:99

Don't know why there's 3 attacks listed against Super LoC since I only have 2 set.
![image](https://user-images.githubusercontent.com/9310914/64933693-4b8d2e80-d814-11e9-8664-c0e3644d88b8.png)

Maybe since the 1st 2 are 3 seconds apart it was a queue issue or the attack failed/dropped and another was issued?
Only thing in ErrorLog is
9/15/2019 11:09:22 AM
9/15/2019 11:09:25 AM
	Error Cloud Script Error: send WB {"ok":false,"err":"Wait 5 seconds"}
9/15/2019 11:32:25 AM

And nope, I can't confirm is there was actually 3 attacks or not :(
