### ISSUE TITLE
Update for new World Boss "Bornag"

### ISSUE THREAD

**Issue by A69Tor** [MatthieuBonne/CQAutomater#11]
There is a new world boss which needs to be accounted for in the UI.

**Comment by MatthieuBonne** [comment]
Done ! Please test. :)

**Comment by Vitae666** [comment]
The Lineup isn't saving. I'm clicking Save, but when I close CQAM and reopen it, it's unset.
The Setting.json file always has this

>   "BorLineup": null,
>   "defaultDQLineup": [
>     "b-day",
>     "masterlee",
>     "raiderrose",
>     "neptunius",
>     "E31",
>     "ageum"
>   ],
> 
Those aren't the heroes I'm selecting.
Also, if the default was supposed to load up, it wasn't either. I removed from null to the default and added my own lineup in there. loaded up and it's working fine. After I remembered to enter them backwards in the setting file at least :)

BUT changes aren't saving for Bor. Tested and changed a hero, saved, and it didn't change in the settings file.

**Comment by MatthieuBonne** [comment]
Thanks ! Better now ?

**Comment by Vitae666** [comment]
Yup :)

**Comment by A69Tor** [comment]
Looks to be working from what I can see as well
