### ISSUE TITLE
Tabs and Indicators out of line with each other

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#12]
![image](https://user-images.githubusercontent.com/9310914/62320480-45164380-b46e-11e9-8591-63f7dbb451fe.png)

**Comment by MatthieuBonne** [comment]
Now that's weird. Your tabs look much smaller than mine ! What's your Windows version ?

**Comment by MatthieuBonne** [comment]
I pushed a change, tell me if it's better. Seems I can't force width for individual tabs, so I forced the same width for all.

**Comment by Vitae666** [comment]
Windows 7 but I don't have that visual setting thing enabled. Like how on the macro creator my level and promotion bars are squished. Had a post on Alya version or on the Kong forums about it.
Might have something to do with that. I prefer the Windows XP view of the Windows rather than those huge close/minimize windows.
I won't be able to check for 3 days. At the hospital with my eldest for a sleep study.

**Comment by Vitae666** [comment]
Perfect :)
Now if only CQMC didn't look like this :) : 
![image](https://user-images.githubusercontent.com/9310914/62431348-d1399c80-b6f4-11e9-960e-a3b2fd2944f7.png)
According to Alya there's nothing that can be done for whatever reason. I have to enable "User visual styles on windows and buttons" under Control Panel > Adjust Visual Effects for it to look like this:
![image](https://user-images.githubusercontent.com/9310914/62431464-bb78a700-b6f5-11e9-864a-043e07fd361c.png)

And honestly, I HATE how it makes my windows and taskbar look. Granted, I can cheat but enabling it, opening CQMC, then disabling it and keep the view, but meh. Why can't it just look like this from the beginning :(
![image](https://user-images.githubusercontent.com/9310914/62431395-473e0380-b6f5-11e9-9cf9-5e26af37e5c0.png)

**Comment by MatthieuBonne** [comment]
Well I guess it could be fixed but I really don't know how, sorry...

**Comment by Vitae666** [comment]
:(
