### ISSUE TITLE
Auction prices update every 30s but CQA every 5m?

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#13]
Is there a background type of knowledge that the Auction knows that if there's 20s left for the auction, and you haven't bid, and the CQA won't refresh in 3m, that it will place the bid for you if it's within your price range?

**Comment by Vitae666** [comment]
Ok, guess what I'm asking is if there's something that might not kick in the bid correctly.
I was in the middle of a bidding war for Sparks and suddenly I lost. 
My max bid is 1025, I have 3554. And at some point, I tried to bid 370, which failed twice in 4 seconds, and then it wasn't refreshed due to the timer, and I lost.
Tho, if I'm reading it right, it looks like it really failed at the 305 bid and I lost there. At least I think, if I understand that "desync" actually means "Next Bid Amount"

> 8/4/2019 9:53:57 PM
> 	FAILED Bid on hero Sparks for: 63UM.
> {"ok":false,"err":"Bid desync 70 63"}
> 8/4/2019 9:54:03 PM
> 	FAILED Bid on hero Sparks for: 63UM.
> {"ok":false,"err":"Bid desync 70 63"}
> 8/4/2019 10:04:57 PM
> 	Bid on hero Sparks for: 188UM.
> 8/4/2019 10:05:01 PM
> 	FAILED Bid on hero Sparks for: 188UM.
> {"ok":false,"err":"Bid desync 207 188"}
> 8/4/2019 10:07:53 PM
> 	Bid on hero Sparks for: 251UM.
> 8/4/2019 10:07:57 PM
> 	FAILED Bid on hero Sparks for: 251UM.
> {"ok":false,"err":"Bid desync 277 251"}
> 8/4/2019 10:09:53 PM
> 	Bid on hero Sparks for: 305UM.
> 8/4/2019 10:09:57 PM
> 	FAILED Bid on hero Sparks for: 305UM.
> {"ok":false,"err":"Bid desync 336 305"}
> 8/4/2019 10:12:03 PM
> 	FAILED Bid on hero Sparks for: 370UM.
> {"ok":false,"err":"Bid desync 10 370"}
> 8/4/2019 10:12:07 PM
> 	FAILED Bid on hero Sparks for: 370UM.
> {"ok":false,"err":"Bid desync 10 370"}

Also, I'm pretty sure that I'd won some of those bids. Not sure why they all say that they failed.
But either way, the end result is the same, I somehow didn't even get close to bidding 1025.

EDIT: Ok, just realized that the lowset bid in the 1000's might be 1,063 not 1,025. Not sure what idiot math I did to get 1,025

EDIT2: Ah. OK. I was under the assumption that every Hero started with a 9 bid. Just seeing that some heroes have different ones like 45 and 181. Unless those themselves are part of the 10% increase and my basic math skills are really in the toilet. Would it be possible to, not at all in a drop down box because that could get long and messy looking, but set the bids to display the exact bids? Like it shows 494 and you click the uparrow, it shows 544 and click once more and it shows 599. But not a hard coded type where in the code it lists all the costs (Like the hero display), just mathematical with the 10% increase. Default cost is 9, but you bid 10, so it starts with 10, then Up arrow is clicked and CQA does the fancy math thing and displays the next 10% increase, and so on. Only thinking of that because for the longest time I had 1000 as the max bid, then I figured out that wasn't close and I did something stupid and thought 1,025 is is and now I'm thinking 1,063. All because I'm not at all sure if every heroes cost is based off the original 9 or if the 45 and 181 are different variations.
I'm prolly explaining that badly and should just STFU :)

**Comment by Vitae666** [comment]
Ok, so I think I see why it's saying I'm failing. Or at least I THINK I see. Either it's trying to bid twice within a few seconds of each other, or it's logging the success as a Fail for some reason. I'm clearly the current highest bidder and didn't fail at the bid.

![image](https://user-images.githubusercontent.com/9310914/62474097-249d0080-b770-11e9-951a-3d77949118f9.png)

Doesn't explain the complete loss the other day tho.

**Comment by Vitae666** [comment]
Guess another example is this
![image](https://user-images.githubusercontent.com/9310914/62502617-589f1280-b7be-11e9-944f-38f0427ead5c.png)
I bid, the timer went from 13s to 1:13m and then down to 10s and the AH never updated to show that I'd even bought it. 
The timer on it was incorrect as well because it was 13 seconds left when I bought it, and that bumped it by a minute in the game, but the AH shows 44 seconds still while it's counted down to 10 seconds in game in the screenshot.
Something's just off somewhere I think :(

**Comment by MatthieuBonne** [comment]
Thanks for all the data, it helps ! Trying to fix that.

**Comment by Vitae666** [comment]
As a small suggestion, maybe when the hero selection is manually changed, maybe do a quick timer check/reset? 
Like sometimes I'd switch to a hero that was close to timing out and it wouldn't put a bid in.
Not sure if it would help. I know that I'm almost 100% sure that the fails I was reporting had nothing to do with switches.
But thinking that if the auction prices update every 30s, maybe the main timer should do that as well?

Edit: just saw the update. Will check it in about 9hrs. Working 😁

**Comment by Vitae666** [comment]
So, this just happened....
I had Flynn on the 2nd slot for the AH, I changed it to Zeith because it was like 30 seconds for it to end. I waited until it was down to 9 seconds, and it didn't place a bid so I manually placed it. AH never changed to show that I'd bid, and then when the timer ran out, it started to count upwards. When the Next Refresh hit, it corrected itself.
The mousemovent over Brynhildr is cause that's where Zeith was. I woulda let the recording continue until the refresh, but my upload speed sucks and didn't want to take an hour to upload :)

[http://youtu.be/rHhQYsJmZ7s?hd=1](http://youtu.be/rHhQYsJmZ7s?hd=1)

**Comment by MatthieuBonne** [comment]
I decreased default update interval, and I'm working on forcing update when a hero switch happens.

**Comment by MatthieuBonne** [comment]
Pushed, please test.

**Comment by MatthieuBonne** [comment]
The "next refresh" AH timer is misleading : it's basically a clone of the WB timer. Don't look at it for now, just test the prices please.

**Comment by Vitae666** [comment]
Will check and let you know. Kinda out of UM's now :)

**Comment by Vitae666** [comment]
BTW, I meant i'm out of UM"s now after getting Santa Claus.
Also, that Failed bid thing still happens

8/12/2019 8:28:55 AM
	Bid on hero Santaclaus for: 700UM.
8/12/2019 8:28:59 AM
	FAILED Bid on hero Santaclaus for: 700UM.
{"ok":false,"err":"Not enough UM"}

700 was my bid and what I won with.

**Comment by Vitae666** [comment]
Latest version:
8/13/2019 11:38:53 PM
	Bid on hero Christmaself for: 724UM.
8/13/2019 11:38:57 PM
	FAILED Bid on hero Christmaself for: 724UM.
{"ok":false,"err":"Not enough UM"}

Wanna guess what happened? :)



If you guessed, I won with the 724 bid you'd be right ;-)

**Comment by Vitae666** [comment]
I was thinking, and I could be off base with it since I don't know the exact way CQA communicates with the game/server, but since usually those "Failed Bid" msgs are about 4-5 seconds after the placed bid, maybe it's because of the time delay with the game refreshing? I mean, I've sat here and seen the in-game counter count to -10 after an auction is over. 
I'm thinking maybe that CQA is going "Oh shit, the old bid is still there! Let me bid again!" And then it fails because while the in-game display hasn't changed, the server knows already that the bid has been accepted so 724 ISN'T the right bid anymore.
Like I said, I don't know where the data is pulled from, where it's sent, what's done with it once it's sent and received. Could be that there's a lag time in-game that after the bid is received it takes a few seconds before the game knows to refresh the display and the database so in the "Current Bid" field in the database it still shows the previous bid until the placed bid is written in.
If that's the case, I guess the FAILED msg will just be there cause there's no real way to have it know.
Dunno. Just spit-balling.

Also, any way to have it know if you WON the Auction? Spit out a msg in the files that says something like "You won the Hero {HeroName}!"

**Comment by MatthieuBonne** [comment]
I think your guess is right ; I'll see if forcing a waiting time between two bids helps.
About winning an auction, it's complicated, Icewizard had nightmares with his gsheet trying to find that information, the best he could do was guessing from last data. I guess we may have a better chance reading from user history but I haven't looked at it closely yet.

**Comment by Vitae666** [comment]
OH!! I thought that there was some database (or where ever you get the infor from) that you could see who won the auction easily. Didn't know it was a task like that. If not, then all good. BUT at that point, that's where that other idea of mine about a pop-up msg saying "You don't need to bid because you already have maxed out this Hero's lvl" comes into play ;-)

**Comment by Vitae666** [comment]
Any update on possibly adding the pop-up msg about having maxed a Hero out like Level does?

**Comment by Vitae666** [comment]
Something is still weird with AH :(

9/9/2019 11:20:28 PM
	Bid on hero Alvitr for: 267UM.
9/9/2019 11:20:33 PM
	FAILED Bid on hero Alvitr for: 267UM.
{"ok":false,"err":"Bid desync 294 267"}
9/9/2019 11:22:51 PM
	Bid on hero Alvitr for: 324UM.
9/9/2019 11:22:58 PM
	FAILED Bid on hero Alvitr for: 324UM.
{"ok":false,"err":"Bid desync 357 324"}
9/9/2019 11:24:54 PM
	Bid on hero Alvitr for: 393UM.
9/9/2019 11:24:58 PM
	FAILED Bid on hero Alvitr for: 393UM.
{"ok":false,"err":"Not enough UM"}
9/9/2019 11:26:52 PM
	FAILED Bid on hero Alvitr for: 477UM.
{"ok":false,"err":"Not enough UM"}
9/9/2019 11:26:56 PM
	FAILED Bid on hero Alvitr for: 477UM.
{"ok":false,"err":"Not enough UM"}

It stopped bidding after that last one. I have 1,173 UM so there shouldn't have been a reason for stopping.
I know that sometimes CQ doesn't update your return of UM from a failed bid right away, but I think it should have updated in the minutes before it ended.
267+324+393 = 984
So, I can understand with that last 477 it wouldn't work because it was 1,461. But my other bids should have been refunded by then.
Don't know why it's not updating.
I've seen a few times after I've lost bids that I'll load up CQ an hour or so later and it won't display my correct UM for a minute or so.
I'm thinking some extra call to the system is made by CQ to update the UM value.
Would explain the above fails as well....I think.

**Comment by Vitae666** [comment]
Woke up. CQA failed on 2 bids because it thought I had 189UM hours later :(
Logged into CQ and it said I had 189. 30 seconds later or so, it updated to 1173. 
CQA went thru 4 60 second refreshes and still says 189.
Including my PC time on here for reference :)
Closing and restarting CQA fixed the UM count.
![1](https://user-images.githubusercontent.com/9310914/64618198-ccc86980-d3ad-11e9-8a5d-db91e196617a.JPG)
![2](https://user-images.githubusercontent.com/9310914/64618216-d651d180-d3ad-11e9-9eea-3bf09db87f8c.JPG)
![3](https://user-images.githubusercontent.com/9310914/64618471-56783700-d3ae-11e9-9531-c19cb02c0659.JPG)
![4](https://user-images.githubusercontent.com/9310914/64618671-b078fc80-d3ae-11e9-9ae4-e76b98403cf4.JPG)

**Comment by Vitae666** [comment]
Suggestion: Whatever call to the server it does when starting up, can it do that when it does the Refresh as well? Would help with correct UM count. I think at least :)

**Comment by MatthieuBonne** [comment]
Yes I'll do that, I'll also look at your other questions, as soon as I find some time. Lots of work these days ! :)

**Comment by Vitae666** [comment]
LOL. I bet. Thanks 😆

Everytime you get an email from me you're prolly like "Ugh! This fucking guy again?!?!"

**Comment by Vitae666** [comment]
What's weird is that I know it USED to fix itself with the UM count. Have no idea why it's not doing it now.

**Comment by Vitae666** [comment]
Actually, heads up that it seems like NONE of the Currencies might be updating unless CQA is restarted.
![image](https://user-images.githubusercontent.com/9310914/64719000-60c13080-d495-11e9-82b6-86bee3a4b3d7.png)
I'd levels ALordKirk about 30 mins ago.

**Comment by MatthieuBonne** [comment]
Improved in next commit. :)

**Comment by Vitae666** [comment]
Just to make sure, this should fix the AH and Levels currency updating in the game reflecting in CQA without a restart needed?
Lose an auction, game refunds your UM, CQA refreshes and it's updated?
Same with Levels. You gain 10 Prana and it'll reflect, i'm guessing after a 4hr refresh?

**EDIT:** 
Ok, yeap. At least for the Level Tab it only updates on a Refresh. CQA leveled Lili X1 and ALordKirk X2 and the Currencies didn't update. I unchecked and rechecked Enable Auto-Leveling and it refreshed the Currencies. Should update the Currencies on a Level I think. Only to avoid confusion. Maybe have it do the Refresh code when it finishes the Level procedure as well? Not sure if that's going to start doing weird things tho with the extra calls.
Waiting on Auction to kick in, but going to assume it'll work the same on there :)

**EDIT 2:**
Ok, admittedly, I am no longer sure WHICH version of CQA I opened now.
I always make a copy of the old one incase of something going horribly wrong so I have a back up.
And I ALWAYS uncheck the "Always ask before running" checkbox that Windows 7 throws at me. 
I closed CQA by mistake just now, and reopened it. And I got the question. It's happened before where the 1st time I run it, if it's very close to when the new version downloaded that it won't give me the msg, but I honestly can't remember if I'd stupidly opened the copy or the new. 
But since the currencies in Level updated on a Refresh, and  it wasn't before (because I'd tried in my post above) I'm 99.5% sure that it was the new one. Damned if I know now. 
Christ, I need another 10 cups of coffee before I head out to work!

**Comment by MatthieuBonne** [comment]
Hmmm. I'll add another refresh after an autolevel happens. Don't want to add too much, spamming the server won't please Gaia. ^^

**Comment by Vitae666** [comment]
Safe to assume that CQA knows how many levels to run over each of the currencies? Could do it at the end of the total run cycle?
Like can it know that it has to run 2PG, 4CC and 1AS and when all 7 levels are done, it does the refresh then?

**Comment by MatthieuBonne** [comment]
Is the issue solved ?

**Comment by Vitae666** [comment]
I think so. I've almost gotten used to closing and reopening every few
hours that I haven't noticed. Not doing auctions right now so I can build
up the 5k UM for the season special.

**Comment by MatthieuBonne** [comment]
Great ! :)
