### ISSUE TITLE
Something get wrong...

### ISSUE THREAD

**Issue by LudoKressh** [MatthieuBonne/CQAutomater#14]
The same error every 30 seconds:

> 06/08/2019 02:00:24
	Impossible d'effectuer un cast d'un objet de type 'Newtonsoft.Json.Linq.JValue' en type 'Newtonsoft.Json.Linq.JArray'.
06/08/2019 02:00:55
	Impossible d'effectuer un cast d'un objet de type 'Newtonsoft.Json.Linq.JValue' en type 'Newtonsoft.Json.Linq.JArray'.

And the application ended up crashing.

**Comment by MatthieuBonne** [comment]
Fixed in next commit :)

**Comment by LudoKressh** [comment]
merci

**Comment by LudoKressh** [comment]
The same error every 30 seconds (LF event):

> 11/08/2019 02:00:08
> 	Impossible d'effectuer un cast d'un objet de type 'Newtonsoft.Json.Linq.JObject' en type 'Newtonsoft.Json.Linq.JArray'.
> 11/08/2019 02:00:38
> 	Impossible d'effectuer un cast d'un objet de type 'Newtonsoft.Json.Linq.JObject' en type 'Newtonsoft.Json.Linq.JArray'.

**Comment by Vitae666** [comment]
He hasn't put up the next commit yet. It's going to keep happening until then.
I've been getting it too
8/11/2019 1:23:05 AM
	Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JArray'.
8/11/2019 1:23:28 AM
	Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JArray'.

**Comment by MatthieuBonne** [comment]
Yes sorry, hadn't found how to fix a problem with the LF gsheet. Looks ok now, I guess I'll commit later today.
