### ISSUE TITLE
AH shows lvl of 1st Hero only

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#17]
I have the 2nd and 3rd one, so I know it's not a "Don't have them" scenario
![image](https://user-images.githubusercontent.com/9310914/63220554-301cfe00-c158-11e9-8499-643aabca5f19.png)
![image](https://user-images.githubusercontent.com/9310914/63220563-72ded600-c158-11e9-80be-c89a44af6e98.png)
Tried entering other Heroes in 2/3 to see if it would force a recheck, but nope :(
Don't get me wrong tho, awesome that it's working for the 1st one at least :)

**Comment by Vitae666** [comment]
BTW, check of the code shows that you only entered:
  main.label134.setText("current: " + PFStuff.heroLevels[a.heroID]);
on the 1st ones code not on auctionHero2Combo and auctionHero3Combo
Somehow tho, I'm betting just adding the same code to all 3 of them isn't what's need
:)

**Comment by MatthieuBonne** [comment]
Aha yes sorry, I thought "I'll test first then add the 2 other", then forgot about it... :D

**Comment by Vitae666** [comment]
:)
