### ISSUE TITLE
LF not working past picking the 2nd card...I think.

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#18]
There's no msgs in Action or Error logs.
Just got home, saw LF was active, checked and 2 were selected (8,10)
Don't know how long it was like that. Was it the 1st round? The 3rd? No idea. :(

**Comment by Vitae666** [comment]
Ok, going to guess that part of the error is that CQA need to be shut down and reloaded for the LF to work. Will this need to be done every time LF happens? Dunno. Will find out next time.
But CQA had crashed, and I reloaded it. Now it seems to work OK

8/18/2019 10:33:11 PM
	New template added : 100-250-10000-75-1000-50-25000-25-150-500-2500-5000
8/18/2019 10:59:14 PM
	 Picking LF cell 0
8/18/2019 10:59:39 PM
	 Picking LF cell 5
8/18/2019 11:00:09 PM
	 Picking LF cell 10
8/18/2019 11:00:11 PM
	New template added : 5000-250-1000-100-50-25000-500-75-25-2500-150-10000

**Comment by Vitae666** [comment]
Just  woke up (8:45am) to a 2 cell selection again.
8/19/2019 2:04:48 AM
	New template added : 75-100-2500-500-1000-250-25-25000-10000-5000-150-50
8/19/2019 3:05:17 AM
	 Picking LF cell 0
8/19/2019 3:05:55 AM
	 Picking LF cell 11
8/19/2019 3:06:16 AM
	Input string was not in a correct format.
8/19/2019 3:06:46 AM
	Input string was not in a correct format.
8/19/2019 3:07:16 AM
	Input string was not in a correct format.
8/19/2019 3:07:48 AM
	Input string was not in a correct format.
8/19/2019 3:08:16 AM
	Input string was not in a correct format.

Couple hundred of those Input string errors :)
With this in the middle of them only once:

8/19/2019 5:03:55 AM
	Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

Nothing in Errorlog regarding any of this tho.

**Comment by Vitae666** [comment]
A thought, and a long shot:

8/19/2019 8:52:58 AM
	New template added : 100-10000-50-25-1000-500-75-5000-250-25000-150-2500
8/19/2019 9:52:59 AM
	 Picking LF cell 0
8/19/2019 9:53:29 AM
	 Picking LF cell 1
8/19/2019 9:53:59 AM
	 Picking LF cell 8
8/19/2019 9:54:01 AM
	New template added : 100-150-5000-75-25000-10000-25-250-1000-500-2500-50
8/19/2019 10:54:31 AM
	 Picking LF cell 0
8/19/2019 10:55:01 AM
	 Picking LF cell 6
8/19/2019 10:55:30 AM
	 Picking LF cell 5
8/19/2019 10:55:35 AM
	New template added : 1000-25-10000-250-75-500-5000-150-25000-100-50-2500

If it's taking 30 seconds between each selection, could it be possible that someone does an update and it's screwing with the selector?
Granted, I'm only seeing it happen on the 3rd one. Hence "Long shot"

**Comment by MatthieuBonne** [comment]
I decreased countdown between cell picks and made sure CQA was logged in to PlayFab (the bug may come from here). We'll see next week if it's fixed. :)
