### ISSUE TITLE
App crashes at launch version 4.3.3.3

### ISSUE THREAD

**Issue by djozz911** [MatthieuBonne/CQAutomater#19]
Hello,

I got this message when using the last version of the automater :

System.Reflection.ReflectionTypeLoadException: Impossible de charger un ou plusieurs des types requis. Extrayez la propriété LoaderExceptions pour plus d’informations.
à System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
à System.Reflection.RuntimeModule.GetTypes()
à System.Reflection.Assembly.GetTypes()
à PlayFab.Internal.PlayFabHttp..cctor()

any ideas ??

thx

**Comment by MatthieuBonne** [comment]
Did you configure your kongid ? Seems like PlayFab denies you access.
Anyway I just pushed an update to write some debug info in ErrorLog.txt ; please send it here.

**Comment by djozz911** [comment]
kongID configured correctly.
I have no problem with ver. 4.3.2.0 or CQMacroCreator.

Will test tomorrow.

**Comment by djozz911** [comment]
I can't find the update.
I've tried older versions, no problem with 4.3.3.2.

**Comment by MatthieuBonne** [comment]
Sorry, yesterday's push wasn't sent for some reason. :\ Please retry with today's update.

**Comment by MatthieuBonne** [comment]
Do you have Newtonsoft.Json.dll & .xml in your CQA folder ? In 4.3.3 I included them in the exe so they're not needed anymore.

**Comment by djozz911** [comment]
> Do you have Newtonsoft.Json.dll & .xml in your CQA folder ? In 4.3.3 I included them in the exe so they're not needed anymore.

Yes, I need them for Alya-N CQMacroCreator.
If I remove them, I get a warning pop-up which I can close and run the Automater.

But with or without Newtonsoft.dll & .xml here's the error I get : 
System.Exception: Cannot find a valid IPlayFabHttp type
   à PlayFab.Internal.PlayFabHttp..cctor()


My Settings.json, just in case
`{
  "KongregateId": "xxxxxxxx",
  "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "actionOnStart": 0,
  "defaultLowerLimit": "30%",
  "defaultUpperLimit": "100%",
  "LoCLineup": [
    "aneptunius",
    "neptunius",
    "pokerface",
    "W30",
    "hosokawa",
    "guy"
  ],
  "MOAKLineup": [
    "defile",
    "pokerface",
    "F30",
    "lordkirk",
    "neil",
    "guy"
  ],
  "KrytonLineup": [
    "geum",
    "pokerface",
    "E30",
    "thert",
    "neil",
    "guy"
  ],
  "DoyLineup": [
    "A30",
    "shygu",
    "pokerface",
    "aneptunius",
    "neil",
    "guy"
  ],
  "BorLineup": [
    "masterlee",
    "guy",
    "neil",
    "W29",
    "crei",
    "acrei"
  ],
  "defaultDQLineup": [
    "defile",
    "pokerface",
    "hosokawa",
    "lordkirk",
    "neptunius",
    "guy"
  ],
  "calcEnabledHeroes": [
    "geror",
    "pontus",
    "shygu",
    "thert",
    "lordkirk",
    "neptunius",
    "dagda",
    "hosokawa",
    "takeda",
    "hattori",
    "bavah",
    "masterlee",
    "pokerface",
    "defile",
    "neil",
    "ashygu",
    "aneptunius",
    "guy",
    "seethe",
    "thewanderer"
  ],
  "DQSoundEnabled": false,
  "autoBestDQEnabled": false,
  "autoDQEnabled": false,
  "autoPvPEnabled": true,
  "autoChestEnabled": false,
  "chestsToOpen": null,
  "autoWBEnabled": false,
  "safeModeWBEnabled": false,
  "pvpLowerLimit": 4,
  "pvpUpperLimit": 5,
  "WBsettings": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    0
  ],
  "bids": [
    {
      "biddingEnabled": true,
      "name": "Leprechaun",
      "maxLevel": 1,
      "maxBid": 8500
    },
    {
      "biddingEnabled": false,
      "name": "",
      "maxLevel": 0,
      "maxBid": 0
    },
    {
      "biddingEnabled": false,
      "name": "",
      "maxLevel": 0,
      "maxBid": 0
    }
  ],
  "autoLevelEnabled": null,
  "bankedCurrencies": null,
  "herosToLevel": null,
  "levelLimits": null,
  "waitAutoLevel": false,
  "instantMaxPriceBid": false,
  "autoEvEnabled": false
}`

**Comment by MatthieuBonne** [comment]
Thanks ; anything in ErrorLog.txt ?

**Comment by djozz911** [comment]
here you go

30/08/2019 14:29:41
	Error in PlayFabHttp
	Impossible de charger un ou plusieurs des types requis. Extrayez la propriété LoaderExceptions pour plus d'informations.

**Comment by djozz911** [comment]
And the full error message window

```
************** Texte de l'exception **************
System.Exception: Cannot find a valid IPlayFabHttp type
   à PlayFab.Internal.PlayFabHttp..cctor()


************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
CQ Auto-follower-claimer-inator
    Version de l'assembly : 4.3.3.0
    Version Win32 : 4.3.3.0
    CodeBase : file:///C:/Users/djozz/Desktop/calc/CQ%20Auto-follower-claimer-inator%20(2).exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.3314.0 built by: NET472REL1LAST_B
    CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Version de l'assembly : 11.0.0.0
    Version Win32 : 4.3.3.0
    CodeBase : file:///C:/Users/djozz/Desktop/calc/CQ%20Auto-follower-claimer-inator%20(2).exe
----------------------------------------
System.Runtime.Serialization
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2558.0 built by: NET471REL1
    CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2053.0 built by: NET47REL1
    CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2053.0 built by: NET47REL1
    CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
```

**Comment by MatthieuBonne** [comment]
Thanks ! I added more debug in errorlog, please retry.

**Comment by djozz911** [comment]
`30/08/2019 15:33:23
	httpInterfaceType
	PlayFab.Internal.IPlayFabHttp
30/08/2019 15:33:24
	Error in PlayFabHttp
	Impossible de charger un ou plusieurs des types requis. Extrayez la propriété LoaderExceptions pour plus d'informations.
`

**Comment by MatthieuBonne** [comment]
You don't have something like this in ErrorLog.txt ?

`30/08/2019 15:16:18
	httpInterfaceType
	PlayFab.Internal.IPlayFabHttp
30/08/2019 15:16:18
	eachType
	<>f__AnonymousType0`2[<token>j__TPar,<kid>j__TPar]
30/08/2019 15:16:18
	eachType
	<>f__AnonymousType1`1[<wc>j__TPar]
30/08/2019 15:16:18
	eachType
	<>f__AnonymousType2`1[<kid>j__TPar]`

**Comment by djozz911** [comment]
Nope, this is all I have

30/08/2019 15:38:33
	httpInterfaceType
	PlayFab.Internal.IPlayFabHttp
30/08/2019 15:38:33
	Error in PlayFabHttp
	Impossible de charger un ou plusieurs des types requis. Extrayez la propriété LoaderExceptions pour plus d'informations.
[ErrorLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/3560113/ErrorLog.txt)

**Comment by MatthieuBonne** [comment]
Ok ; please retry latest exe, you should see something starting with "error detail". Sorry it takes so long, my guess is a .NET version issue, but I have to find the missing DLL.

**Comment by djozz911** [comment]
30/08/2019 15:58:01
	httpInterfaceType
	PlayFab.Internal.IPlayFabHttp
30/08/2019 15:58:01
	error detail : 
	Impossible de charger le fichier ou l'assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou une de ses dépendances. Le fichier spécifié est introuvable.
Fusion Log:
AVT : la journalisation de liaison d'assembly est désactivée.
Pour activer la journalisation des échecs de liaison d'assembly, attribuez la valeur 1 à la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD).
Remarque : une certaine perte de performance est associée à l'enregistrement dans le journal des échecs de liaison d'assembly.
Pour désactiver cette fonctionnalité, supprimez la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog].

[ErrorLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/3560198/ErrorLog.txt)

I have to go.
I leave 4.3.2.0 running for followers claim.

Thanks for everything and have a nice week-end !

Djz

**Comment by MatthieuBonne** [comment]
Great, I think I found it. Just uploaded a new version. Have a nice week-end too !

**Comment by djozz911** [comment]
Hello,

2 tries... no luck with last version :'(

[ErrorLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/3564653/ErrorLog.txt)

**Comment by MatthieuBonne** [comment]
Ok, I tried updating some libs to force using a more recent System.Net.Http, tell me if it helps.

**Comment by djozz911** [comment]
Same error...

`03/09/2019 13:23:21
	httpInterfaceType
	PlayFab.Internal.IPlayFabHttp
03/09/2019 13:23:21
	error detail : 
	Impossible de charger le fichier ou l'assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou une de ses dépendances. Le fichier spécifié est introuvable.
Fusion Log:
AVT : la journalisation de liaison d'assembly est désactivée.`

Am I the only one who gets this error ?

**Comment by MatthieuBonne** [comment]
Seems so :\ What versions of .NET framework do you have ?

**Comment by djozz911** [comment]
I have 4.7.1

edit : I've just forced a windows update, and guess what... 4.3.3.3 doesn't crash anymore !!

Thx for everything.

**Comment by darkzerp** [comment]
Okay, as I had the same problem as djozz911 I would like to share with you how I solved it.
After reading this issue, I thought that the problem can be cause by the .Net Framework, so I installed the newest version 4.8 and the problem was solved.
Before I had the version 4.7.1, so I think this can be the cause of the problem.
