### ISSUE TITLE
Auction house does not appear to be placing bids

### ISSUE THREAD

**Issue by A69Tor** [MatthieuBonne/CQAutomater#2]
I am currently well below the maximum bid set, but at each refresh the Automator does not appear to be placing a bid for the desired characters.  Settings are set as follows:

Rua -> Up to Level 1 -> Max 2004 (Current 220)

"Bid immediately if last bid allowed by max price is possible"

**Comment by A69Tor** [comment]
Took a look in the code, and it appears this is "As intended".  It appears bids are only placed when there are less than 40 seconds left in the auction, is that correct?

**Comment by MatthieuBonne** [comment]
Yes I guess it's as intended, to prevent abuse and server overload, but I think the checkbox could become a "force bid" button.

**Comment by MatthieuBonne** [comment]
After some thought I won't do this "force bid" thing ; so... AH works as intended for now.
