### ISSUE TITLE
Twitter Coupon Question

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#20]
Might as well start a new post than continue with off-topic questions on that other post :)

So, I have the latest version with Coupons back in. Is it supposed to randomly switch to whatever this "id:" thing is? It was displaying "id:" on the previous version which was why I'd asked about where it went in the other post.
When you put it back in, it was back to displaying the Coupon bit. At some point in the past 14hrs it's changed from "Last Coupon detected:" to "id:" again....
I don't know what it is because it's not my Authentication Ticket nor Kong ID. But I'm not going to post it cause I dunno what it is :)
![image](https://user-images.githubusercontent.com/9310914/64130926-57e4a680-cd93-11e9-8048-d94b6e536915.png)
I closed CQA, restarted it, and it's back to "Last coupon detected:"

**Comment by MatthieuBonne** [comment]
Oh sorry, it's a tweet id I used for debug, I'll remove it in next commit ! ^^

**Comment by Vitae666** [comment]
OK, kewl. Didn't know what was happening. It just switched to it and I was like "the heck is that?" LOL
