### ISSUE TITLE
Not 100% sure, but everytime there's a write error CQA crashes

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#21]
Whenever I crash, I will open the ExceptionLog.txt file and it mentions the below.
I get the same problem when it says the same about saving to ErrorLog.txt

> 9/3/2019 8:21:53 PM
> System.IO.IOException: The process cannot access the file 'C:\Users\jweiss\Desktop\MISC\CosmosQuest\ActionLog.txt' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
>    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
>    at System.IO.StreamWriter..ctor(String path, Boolean append)
>    at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
>    at CQFollowerAutoclaimer.AutoEvent.<EventTimer_Elapsed>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
>    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
> 

Unrelated Side Note that I don't want to make another topic for:
AutoEvent.cs
- CouponTimer.Interval = 12 * 60 * 60 * 1000; // 12h
+ CouponTimer.Interval = 8 * 60 * 60 * 1000; // 12h
The + one isn't 12h ;-)
Just to avoid code viewer confusion LOL

**Comment by MatthieuBonne** [comment]
Weird, dunno why these files would be opened twice... Do you have multiple CQA running ?

Code comment : nice catch ^^

**Comment by Vitae666** [comment]
Nope. Just the 1. It's common too. At least every other day.
Could be a conflict with writing about an auction and a level and DQ all at the same time?
I've looked in the files when it happens and never seen anything weird.
BUT, this time I did....I lost internet for a bit. Having a bit of a hurricane here in FL :)

9/3/2019 8:21:53 PM
	Error in PFStuff
	The operation has timed out
9/3/2019 8:21:53 PM
	Error in PFStuff
	The operation has timed out
9/3/2019 8:21:53 PM
	Error in PFStuff
	The remote name could not be resolved: 'cosmosquest.net'
9/3/2019 8:21:53 PM
	Error in PFStuff
	The remote name could not be resolved: 'cosmosquest.net'
9/3/2019 8:21:53 PM
	Error in PFStuff
	The remote name could not be resolved: 'cosmosquest.net'

Seems CQA wanted to write 5+ things at the same second. I'd lost internet about 5 mine before this.
Have the same time out msg 5 times before this, but spaces out between 30 seconds and over a minute. No idea why CQA went into over time after that

9/3/2019 8:17:16 PM
	Error in PFStuff
	The operation has timed out
9/3/2019 8:17:51 PM
	Error in PFStuff
	The operation has timed out
9/3/2019 8:18:52 PM
	Error in PFStuff
	The operation has timed out
9/3/2019 8:20:32 PM
	Error in PFStuff
	The operation has timed out
9/3/2019 8:20:42 PM
	Error in PFStuff
	The operation has timed out

Additional Side question about the Logs: What spacing do you use between the info (Time/Info1/Info2)?
Whenever something is pasted in here, it acts like an Enter and Tab all in one.
I look at the logs, and it just looks like a Tab. But after the time and Info1 I can press the left arrow key twice before it moves. So, there's something there. Damned if I know what tho :)

**Comment by MatthieuBonne** [comment]
I guess I should rework the log output to buffer everything. I'll keep that in mind ! ;)

**Comment by Vitae666** [comment]
Ok, so I took a dive into the code for doing the logs and found out why when pasting to here it puts things on separate lines: \n\t
For some reason in the logs it sees the \n but doesn't do it, but here it likes it and makes it do a second line.
Well, at least now I know :)
Must be some Notepad/Wordpad difference. I use Notepad usually. Didn't think to look in Wordpad :)
![image](https://user-images.githubusercontent.com/9310914/65392112-f767da00-dd3e-11e9-9ddb-5b30831d9423.png)

**Comment by Vitae666** [comment]
Haven't had this in a while. Might as well close it.
