### ISSUE TITLE
LF Request and questions

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#22]
Ok, so damned if I EVER knew this, but you can only do LF 8 times. I honestly never seen a counter on there like there is one for the Match Pair one.

Is there a way to delay LF from running until 8-9 hrs before it ends so that there are enough data points in the spreadsheet to get the optimal picks?

Also, I'll be honest, I don't know where it's getting the "New Template Added" info from. If it's from the sheet, I'm pretty sure that there's more templates added per hour.
It's looking like it adds a new template after the picks, but I don't know what that means. Or is that the layout of the template that was just played? 
Is CQA not getting the templates from the sheet? Because the picks aren't great if it's using the sheet from what I see :(
If not, then I guess adding a delay won't do anything. But what is it adding the new template about? Hoping to get better selections by the 8th pick? Cause that wasn't a good pick at all LOL

**Comment by MrOzzy86** [comment]
Some of us are wondering if this recent update to include LF in the automator is what's causing the sudden 200-300% increase in templates we've seen the last two LF events (and in turn making LF worse for everyone as the sheet becomes less effective the more templates there are).
AFAIK the amount of templates generated is tied to participation (which is at it's lowest ever right now), so we shouldn't be seeing so many templates... and Gaia has told me they've not changed anything recently.
I'm not very code/script literate, but can you see any way the automator could be causing this?
If so please look into it, thanks!

**Comment by MatthieuBonne** [comment]
Vitae : you may wait before enabling events manually. Imho it's fair to give everyone the same chances : CQA ain't here to advantage only players using it. ;)
Ozzy : CQA only gives Alya's/pebl's sheet to everyone, the mechanism is still the same. My guess is that some players have lots of alts, never bothered to add templates coming from them (they probably didn't even do their 8 draws), and now we "benefit" from their templates. Afaik I'm around 6/8 25k picks, I think I was around 7/8 before. If players want to prevent CQA from adding templates, honestly I don't mind... Maybe Alya has some opinion ?
Or what about writing the player name instead of CQA in the sheet, so we can see if someone is "responsible" from the spam ?

**Comment by MrOzzy86** [comment]
It's not about the adding of templates to the sheet, if they have been generated it's good for the information to be there for ppl to see/use.
We're trying to figure out why so many unique templates are being generated in the first place.
Even when the player base was twice what it is now, we never saw anything higher than 150 unique templates per LF.

The last two weeks are above 300.
Gaia told me that they haven't changed anything on their end, so we're wondering why so many unique templates are even being created per event. I don't think a slight uptick in participation from people using the automator to get them done/doing them on alts wouldn't account for that.

I haven't used the automator in a while, so I don't know how it works for LF, but I'm asking if there is anyway it could be interacting with the CQ server to unintentionally generate more templates somehow. (like i said, i am not code/script savvy, so I don't know how/if that's possible).

**Comment by Vitae666** [comment]
Ozzy: Don't think CQA would be adding anything to the code of CQ to make more. It would be one thing if the CQA template uploads were unique and the only ones that were like that. That is something that I guess could be looked at.
Also, not sure why having more templates added would make the sheet less effective. If nothing else it would be more. Unless you meant due to potential faked data. Wouldn't put it past trolls to screw with it and keep a copy of their own with their altered entries excluded.
Would Gaia be able to verify which templates WERE the ones that were added? Like look at the sheet and go "Nope! This one wasn't supposed to be there!" And if it winds up being CQA then we know that it's uploading them wrong.
Granted, I never actually looked to see if what was on screen was what it said it uploaded. I didn't even know until today that it even did that :)

Matt: Meh :-P
I kinda feel like this whole thing IS an advantage over non-users. I know I would have stopped playing a while ago if it wasn't for this, the CQMC and CQCalc. :)
But I understand. I'll just need to remember that LF is after Dungeon so I can disable it...AND remember to turn it on. LOL
Speaking of, exactly what time in EST do events start? Just so I know what time I have to turn it back on to get the 8 in. I feel like sometimes they start at different times. I've had some start at X time and I swear the next week it's another.

This was what I had this round. 3/8 25K
![image](https://user-images.githubusercontent.com/9310914/64279064-3b27aa80-cf1c-11e9-90f3-c2f22afc756d.png)

For some reason the 1st template shows it was uploaded 3 times. 
9/3/2019 8:00:05 PM	 Picking LF cell 1
9/3/2019 8:00:17 PM	 Picking LF cell 7
9/3/2019 8:00:27 PM	 Picking LF cell 4
9/3/2019 8:00:31 PM	New template added : 100-25000-5000-25-250-150-10000-500-1000-75-50-2500
9/3/2019 8:30:32 PM	New template added : 100-25000-5000-25-250-150-10000-500-1000-75-50-2500
9/3/2019 8:56:57 PM	New template added : 100-25000-5000-25-250-150-10000-500-1000-75-50-2500

**Comment by MrOzzy86** [comment]
@Vitae
It's more like, maybe spam requests to the server for LF data/info could be causing it to generate extra templates or something, I really don't know how/why it could happen.

More templates being generated more often means you're a) more likely to get a new template, and b) the sheet is less effective when there are so many templates because you get splits.
So even tho you are getting an already found template, the last pick for 25k is often a 2/3/4 way split, so you more often than not miss the 25k anyway.
Back when the average of overall templates by the end of the day was only 100-125 only a small handful of final picks would be splits, when there are 250-300+ almost every final pick is a split.
(if you're not sure what I mean, go to the actual sheet and look at the auto-decision tree to see what I mean)

In chat today are lot of people are talking about being at 3-5/8 25k's when the 'average' before this sudden increase in templates was around 7/8.

**Comment by MatthieuBonne** [comment]
To be clear and simple, CQA : 
- reads data from the gsheet (pebl's auto tree, nothing new)
- sends server requests following the gsheet advice (exactly like human clicks)
- sends results to the gsheet, where a duplicate check is done before adding a template.
I understand the issue and don't minimize it at all, I just think we have more CQA users than we thought. Events were a cool way to make a few hundreds of players busy, but using a gsheet (or a calc) to optimize results was too much for some. Add 50 players like that, give them CQA, and maybe that's all there is.

I can do something to know more : collect some data about players using CQA (player name mostly, maybe LF count). That's quite easy, but obviously I always avoided that. If you guys are ok with that, I'll do it before next LF.

**Comment by Vitae666** [comment]
I have no problem with my name being posted.
 I'd suggest tho that it be an option and not mandatory. Some might have an issue. Tho, why they would since you need (I think) to have your name for WB's. But you never know.

**Comment by Alya-N** [comment]
```
GaiaByte: i used real randoms this week instead of time
GaiaByte: random safe xD instead of just using server time
GaiaByte: I checked and there were too many collisions so you must be organizing yourselves
```
```
Patch Notes 4.4
Lucky Followers has also been updated to be truly random, and no longer random based on time. 
```
Mystery solved. Very upsetting news.

**Comment by Vitae666** [comment]
So, does that mean that the sheet is now obsolete?
Picking cells 0, 1, 2 is just as viable as 3, 8, 11 because it could be anything?

**Comment by MatthieuBonne** [comment]
That's upsetting indeed, and somewhat childish. Gaia didn't mind top players using a gsheet and outpacing idlers in his new EM strategy, but when we give the tool (in an easier form) to idlers, he changes his mind ? Sigh.

**Comment by Vitae666** [comment]
Closing this because of LF is now completely random, no need to wait for more templates to be added for better results.

**Comment by Vitae666** [comment]
Oh, question (You hate me, admit it)!
Since LF is now supposedly completely random, there's a really good chance that there will be far fewer results posted to the sheet now. Will CQA be updated to just pick some random 3 cards?
What I mean is, if the sheet is shutdown because there's no need for it, what kinda fun crashes can we expect from CQA. 
Obviously, not saying that the sheet will be, but if there's no need for it, Alya might not see the need to keep it around.

**Comment by MatthieuBonne** [comment]
I think we should wait for @Alya-N 's opinion. Is the new LF really unpredictable ?

**Comment by Alya-N** [comment]
I'm still keeping the spreadsheet in hopes that maybe LF RNG will get reverted.
From what I've seen, it is possible to get duplicates, but only if it's being claimed at the exact same time, so not very useful unless we somehow reverse-engineer the RNG that is used.

**Comment by MatthieuBonne** [comment]
Ok, let's keep it this way for now.

**Comment by Vitae666** [comment]
Ok. Closing this one up cause Matt's prolly tired of seeing my name on the Issues board ;-)

**Comment by Vitae666** [comment]
Seems LF's gone a bit weird now and only just noticed it. Went to work before it started, came back, went to sleep, just woke up. Only now noticed that LF's actions on the Events tab kept flashing picks. And it should have ended hours ago
But I THINK it's been working? I closed CQA down, opened up CQ, looked at followers and it's counting down and has the picks flipped.
So I really don't know.
```
9/21/2019 8:00:31 PM
	 Picking LF cell 6
9/21/2019 8:00:36 PM
	 Picking LF cell 6
9/21/2019 8:00:48 PM
	 Picking LF cell 9
9/21/2019 8:01:01 PM
	 Picking LF cell 10
9/21/2019 8:02:41 PM
	New template added : 100-25-50-75-25000-500-5000-150-1000-10000-2500-250
9/21/2019 8:03:10 PM
	New template added : 100-25-50-75-25000-500-5000-150-1000-10000-2500-250
9/21/2019 8:03:33 PM
	New template added : 100-25-50-75-25000-500-5000-150-1000-10000-2500-250
9/21/2019 8:16:25 PM
	 Picking LF cell 6
9/21/2019 8:16:40 PM
	 Picking LF cell 5
9/21/2019 8:16:49 PM
	 Picking LF cell 9
9/21/2019 8:18:19 PM
	New template added : 25000-50-2500-1000-75-150-250-500-5000-100-10000-25
9/21/2019 8:19:04 PM
	The operation has timed out
9/21/2019 8:19:35 PM
	The operation has timed out
9/21/2019 8:32:21 PM
	 Picking LF cell 6
9/21/2019 8:32:37 PM
	 Picking LF cell 8
9/21/2019 8:32:51 PM
	 Picking LF cell 4
9/21/2019 8:34:32 PM
	The operation has timed out
9/21/2019 8:35:04 PM
	The operation has timed out
9/21/2019 8:35:35 PM
	The operation has timed out
9/21/2019 8:36:07 PM
	The operation has timed out
9/21/2019 8:36:52 PM
	The operation has timed out
9/21/2019 8:37:21 PM
	The operation has timed out
9/21/2019 8:37:53 PM
	The operation has timed out
9/21/2019 8:38:25 PM
	The operation has timed out
9/21/2019 8:38:57 PM
	The operation has timed out
9/21/2019 8:39:33 PM
	The operation has timed out
9/21/2019 8:40:06 PM
	The operation has timed out
9/21/2019 8:40:37 PM
	The operation has timed out
9/21/2019 8:41:11 PM
	The operation has timed out
9/21/2019 8:41:48 PM
	The operation has timed out
9/21/2019 8:42:23 PM
	The operation has timed out
9/21/2019 8:42:55 PM
	The operation has timed out
9/21/2019 8:43:27 PM
	The operation has timed out
9/21/2019 8:43:59 PM
	The operation has timed out
9/21/2019 8:44:31 PM
	The operation has timed out
9/21/2019 8:45:09 PM
	The operation has timed out
9/21/2019 8:45:38 PM
	The operation has timed out
9/21/2019 8:45:58 PM
	Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
9/21/2019 8:45:58 PM
	Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
....
9/22/2019 10:18:58 AM
	The operation has timed out
9/22/2019 10:19:29 AM
	The operation has timed out
9/22/2019 10:19:59 AM
	Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
9/22/2019 10:20:01 AM
	The operation has timed out
9/22/2019 10:21:06 AM
	The operation has timed out
9/22/2019 10:21:38 AM
	The operation has timed out
9/22/2019 10:21:47 AM
	 Picking LF cell 6
9/22/2019 10:21:58 AM
	 Picking LF cell 6
9/22/2019 10:22:06 AM
	Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
9/22/2019 10:22:10 AM
	The operation has timed out
9/22/2019 10:22:29 AM
	 Picking LF cell 6
9/22/2019 10:22:31 AM
	 Picking LF cell 11
9/22/2019 10:22:55 AM
	 Picking LF cell 11
9/22/2019 10:23:00 AM
	 Picking LF cell 11
9/22/2019 10:23:24 AM
	 Picking LF cell 9

9/22/2019 10:39:25 AM
	Error Cloud Script Error: Send LF {"ok":false,"err":"Already picked '6'"}
9/22/2019 10:39:37 AM
9/22/2019 10:39:37 AM
	Error Cloud Script Error: Send LF {"ok":false,"err":"Already picked '6'"}
9/22/2019 10:39:47 AM
9/22/2019 10:39:49 AM
	Error Cloud Script Error: Send LF {"ok":false,"err":"Already picked '6'"}
9/22/2019 10:39:56 AM
9/22/2019 10:39:57 AM
	Error Cloud Script Error: Send LF {"ok":false,"err":"Already picked '6'"}
9/22/2019 10:40:26 AM
9/22/2019 10:40:26 AM
	Error Cloud Script Error: Send LF {"ok":false,"err":"Already picked '11'"}
9/22/2019 10:40:27 AM
9/22/2019 10:40:30 AM
	Error Cloud Script Error: Send LF {"ok":false,"err":"Already picked '11'"}
9/22/2019 10:40:48 AM
9/22/2019 10:40:50 AM
	Error Cloud Script Error: Send LF {"ok":false,"err":"Already picked 3 times"}
9/22/2019 10:41:06 AM
9/22/2019 10:41:06 AM
	Error Cloud Script Error: Send LF {"ok":false,"err":"Already picked 3 times"}
9/22/2019 10:41:09 AM
9/22/2019 10:41:10 AM
	Error Cloud Script Error: Send LF {"ok":false,"err":"Already picked 3 times"}
```

**Comment by MrOzzy86** [comment]
Gaia just fixed it mid-day.
New values have been added and he reset the attempts for everyone.

**Comment by Vitae666** [comment]
What was wrong?
And I've still been getting those errors Timed and Char within the past 20 mins.
I closed CQA down and restarted it and with the last pick seems like everything went ok except for the multiple attempts.

**Comment by MrOzzy86** [comment]
They were meant to have patched in new values to buff LF to make up for the random change.

**Comment by Vitae666** [comment]
Still getting the errors in the ActionLog. I can only assume that it's related to LF because I've had the updated commit since 9/17 and this is the 1st time that it's popping up. 
Won't know 100% until LF is done with.

**Comment by Vitae666** [comment]
Don't know what time LF finished, or if it was related to my last pick being done, but 
9/22/2019 12:21:52 PM
	The operation has timed out
And never got it nor the char msg again.

**Comment by MatthieuBonne** [comment]
Auto LF just picks randomly now.
