### ISSUE TITLE
Snake auto-event.

### ISSUE THREAD

**Issue by MrOzzy86** [MatthieuBonne/CQAutomater#23]
Is there anyway to make it send another attempt after it's already run once?

**Comment by MatthieuBonne** [comment]
Hi, yes and no : we can send anything we want, there seems to be no score control... Therefore, to prevent abuse (which could wake Gaia and make him angry ^^), I made sure CQA stopped attempts once a score >=180 had been sent.

**Comment by MrOzzy86** [comment]
Well we know others have sent scores in b4, (other than a couple people known to be Snake gods, most of the 300+ scores aren't real attempts I would guess)
i believe it's capped at 320 since the Easter update and won't accept anything higher.

Thanks.

**Comment by MatthieuBonne** [comment]
You can also see my best score ever isn't a multiple of 3, which should have raised some warning if the server code had been done seriously. ^^
CQA gives 180-270 now, I think it's "fair" since very good snakers can do 280-290.

**Comment by MrOzzy86** [comment]
I'm curious, I tried editing some of the values in AutoEvent for an alt (int score = rnd.Next(60, 90) * 3;) and it didn't change anything. I tried 90,105 for example and the score sent was still between 180-270.
Am I missing something? ^^

**Comment by MatthieuBonne** [comment]
Did you compile the exe ? ^^

**Comment by monsenanna** [comment]
Will not compile due to missing twitter.cs from repo

**Comment by Vitae666** [comment]
Wait...HUH? CC plays itself? Shit...I thought all it did was let you know that the event was active and that it told you your Highest Score ever gotten mistakenly as your current score. I've never seen it show anything other than 210.
I had 0% idea that CC did anything but report. WOW...Ok, that just made this more awesome :)

**Comment by MatthieuBonne** [comment]
Hehe. Thanks, and sorry for the lack of info. :)

**Comment by MatthieuBonne** [comment]
> 
> 
> Will not compile due to missing twitter.cs from repo

Twitter.cs includes Twitter API keys, you need an account, then it looks like this :
namespace CQFollowerAutoclaimer
{
    static class Twitter
    {
        public static string ConsumerKey = "zzz";
        public static string ConsumerSecret = "zzz";
        public static string OAuthToken = "zzz";
        public static string OAuthTokenSecret = "zzz";
    }
}

I plan to find a way to let people compile without it (therefore disabling autocoupons).

**Comment by Vitae666** [comment]
Why would you need a twitter account to use autocoupons? You can view tweets without an account or being signed in.

**Comment by MatthieuBonne** [comment]
Don't think so ; you can either view your own feed (with simple user credentials), view anyone's through a dev api key, or use a bot to gather http data (scraping). The last option would have our IPs banned quite fast...

**Comment by Vitae666** [comment]
Dunno, but, at least to me, it seems like you can view a twitter page of someone elses when not logged in perfectly fine. I'll leave myself logged off to see if it stops working. 
I don't even use Twitter except for contests that need to me to send a tweet about how cool they are LOL

![Tweet1](https://user-images.githubusercontent.com/9310914/64923147-3c22cc80-d7a5-11e9-9faf-cfc2c013a664.JPG)
![Tweet2](https://user-images.githubusercontent.com/9310914/64923152-45ac3480-d7a5-11e9-84d8-f6d79b27d152.JPG)

**Comment by Vitae666** [comment]
The one difference that I do see between logged in and logged out is that when I click a tweet while logged in, it opens up as a new page. But when logged out, I get a popup.

**Comment by MatthieuBonne** [comment]
That's http, we would need to scrape the page. If I build a scraper in CQA we'll likely be in trouble. What we can do is scrape in a gsheet (Krowi's ?), once per day, then read the sheet with CQA.

**Comment by Vitae666** [comment]
Damn. that's weird. See I don't know squat :)
But, if I can ask, how have I claimed a coupon that came out after I'd logged out....
![image](https://user-images.githubusercontent.com/9310914/64969017-22e75200-d871-11e9-812d-4b272f25ce10.png)

**Comment by Vitae666** [comment]
Still successfully getting the Coupons even tho I'm not logged in....

9/17/2019 7:25:45 PM
	 Sending coupon bQTYzZ9Ik7

**Comment by MatthieuBonne** [comment]
That's the point : CQA doesn't use YOUR (user) credentials, but MINE (as developer). Hence the hidden Twitter.cs ! ;)

**Comment by Vitae666** [comment]
aaahhhh LOL

**Comment by Vitae666** [comment]
> > Will not compile due to missing twitter.cs from repo
> 
> Twitter.cs includes Twitter API keys, you need an account, then it looks like this :
> namespace CQFollowerAutoclaimer
> {
> static class Twitter
> {
> public static string ConsumerKey = "zzz";
> public static string ConsumerSecret = "zzz";
> public static string OAuthToken = "zzz";
> public static string OAuthTokenSecret = "zzz";
> }
> }
> 
> I plan to find a way to let people compile without it (therefore disabling autocoupons).

So, if I wanted to test something on my own, how do I go about it?
Forgot about needing to do a Twitter.cs file, but it was throwing an error about missing Secret.cs
How do I get the strings needed for the Twitter.cs file and heck am I supposed to do about the Secret.cs file since I'll assume it's got stuff in there that we aren't allowed to see.

**Comment by MatthieuBonne** [comment]
I renamed Twitter.cs to Secret.cs, now that's the only file needed. He loks like this : 
```
namespace CQFollowerAutoclaimer
{
    static class Twitter
    {
        public static string ConsumerKey = "...";
        public static string ConsumerSecret = "...";
        public static string OAuthToken = "...";
        public static string OAuthTokenSecret = "...";
    }

    static class MySQLAuth
    {
        public static string user = "...";
        public static string pass = "...";

    }
}
```
You should be able to compile and run CQA with that, it will just fill Action.log with warnings. I'm going to improve that.

Also, while we're in Snake thread, I'm raising lower threshold to 200.

**Comment by Vitae666** [comment]
Had a feeling, but wasn't sure since I saw a twitter.cs entry in some file
that had something to do with ignoring things.

But how would one get their own strings to fill in there? Maybe have them
in the settings.json file like the kong info?

**Comment by Vitae666** [comment]
> I renamed Twitter.cs to Secret.cs, now that's the only file needed. He loks like this :
> 
> ```
> namespace CQFollowerAutoclaimer
> {
>     static class Twitter
>     {
>         public static string ConsumerKey = "...";
>         public static string ConsumerSecret = "...";
>         public static string OAuthToken = "...";
>         public static string OAuthTokenSecret = "...";
>     }
> 
>     static class MySQLAuth
>     {
>         public static string user = "...";
>         public static string pass = "...";
> 
>     }
> }
> ```
> 
> You should be able to compile and run CQA with that, it will just fill Action.log with warnings. I'm going to improve that.
> 
> Also, while we're in Snake thread, I'm raising lower threshold to 200.

Am I forgetting a mention in a build since Apr 6, where needing actual info in Secret.cs is needed? Or would that only be needed to be filled in if you aren't already autologged into Twitter?
Asking cause in my PVP test build from 5/9 @ 3:08PM EST, I've collected all the coupons. 
And there's no "Oh maybe I accidentally started up 'normal CQA'" cause I wasn't even home when they collected.
