### ISSUE TITLE
Lottery Request

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#24]
As with everything I ask, I don't know if it's doable.
Possible to add a "Buy X Amount" of Lottery tickets to the Event Tab?

Reason I'm not sure if it's doable is because I don't know if it's like how the Daily Chest works where certain rewards can't be awarded because it's a Server/Client disconnect. Unless with the progress you've made with adding Events, it IS now possible :)

**Comment by MatthieuBonne** [comment]
Sure it can be done. But well, not now, sorry, too busy. ^^

**Comment by MatthieuBonne** [comment]
It's coded, I'll test it next thursday ; if all goes well, I'll release it for next time.

**Comment by MatthieuBonne** [comment]
Done
