### ISSUE TITLE
MC Gone Wild!

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#27]
Posted this on the Build note, but something else happened after that I just noticed.

Just as heads up, this is showing for MC (not calling it PG anymore :-P )
![image](https://user-images.githubusercontent.com/9310914/65065358-47fec200-d950-11e9-90b2-708d5f34cf3a.png)
9/17/2019 1:35:21 PM
	 Picking PG cell 1
9/17/2019 1:35:22 PM
	 Sending Adventure (2, 100%)
9/17/2019 1:35:26 PM
	 Sending coupon bQTYzZ9Ik7
9/17/2019 1:35:53 PM
	 Picking PG cell 1
9/17/2019 1:35:53 PM
	 Sending Adventure (2, 100%)
9/17/2019 1:36:24 PM
	 Picking PG cell 1
...
...
...
9/17/2019 2:13:40 PM
	 Picking PG cell 1
9/17/2019 2:13:41 PM
	 Sending Adventure (2, 100%)
9/17/2019 2:14:12 PM
	 Picking PG cell 1
9/17/2019 2:14:12 PM
	 Sending Adventure (2, 100%)
9/17/2019 2:14:43 PM
	 Picking PG cell 1

Not sure why it's even trying to DO Adventure since you don't have anything selectable as choices on which one to do or how many. 
Tho, I'd suggest this one be one that has a checkbox so that we can select if we actually want/can afford to do them. Along, of course, with a selection of which of the 3 and how much to put into it.

**Comment by MatthieuBonne** [comment]
Strange it tried several times. But I agree with you, we need individual checkboxes and options for events. I'm mostly afk this week so... Next week hopefully !

**Comment by Vitae666** [comment]
Yeah, had to disable Events until today.
I re-enabled it just now and PG is normal. Not sure, but maybe some weird overlap that MC tries to activate at the same time as Adventure in CQA?
![image](https://user-images.githubusercontent.com/9310914/65167790-3af5d780-da11-11e9-9513-ea06abab6829.png)
