### ISSUE TITLE
Lost DoyLineup & BorLineup

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#29]
I had left the "Auto WB won't work right" username msg box open while I was composing the other "issue" and suddenly I got a box saying that I had empty lineups. I clicked OK on both windows and Doy and Bor were empty. It was removed from the settings as well.

```
  "LoCLineup": [
    "ageum",
    "W31",
    "raiderrose",
    "aurora",
    "thert",
    "athert"
  ],
  "MOAKLineup": [
    "aurora",
    "blossom",
    "ageum",
    "petry",
    "thert",
    "athert"
  ],
  "KrytonLineup": [
    "ageum",
    "E32",
    "thert",
    "takeda",
    "athert",
    "bavah"
  ],
  "defaultDQLineup": [
```

It's all good. I had a backup of the settings file with the lineup so I was able to restore them.

**Comment by Vitae666** [comment]
GOT IT!
It's the Macro Setting Creator in the Macro Creator!
I'd run it cause of disabling the "too many heroes" warning.
It didn't add Doy or Bor's lineups.
It also didn't add a few other things.

```
 ],
  "instantMaxPriceBid": true,
  "warnManyHeroes": false
}

```
```
 ],
  "waitAutoLevel": false,
  "instantMaxPriceBid": true,
  "autoEvEnabled": true,
  "warnManyHeroes": false
}
```

Noticed it when I went to the Events tab and it was disabled. Took a look at the Setting.json and noticed the 2 missing lines

**Comment by MatthieuBonne** [comment]
Should be fixed now ! :)
