### ISSUE TITLE
Automater Crashes

### ISSUE THREAD

**Issue by robgw84** [MatthieuBonne/CQAutomater#3]
The automater is crashing for some reason, it seems to have something to do with the auction house from what I could get out of the details, and maybe the world boss too. This is what it shows in the details of the problem.

`************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CQFollowerAutoclaimer.AuctionHouse.loadAuctions(Boolean getData)
   at CQFollowerAutoclaimer.AutoWB.<getWebsiteData>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)`

**Comment by MatthieuBonne** [comment]
Were you using the latest exe ? I added some fixes recently to prevent these crashes.

**Comment by robgw84** [comment]
Yeah, I just downloaded it to see if that helped before I posted and it did the same thing.

However a couple minutes after it happened I noticed the servers were down so that may have been what caused it.

**Comment by MatthieuBonne** [comment]
Yes it's often related to server issues but that's what I'm trying to prevent. :) I'll take another look at it.

**Comment by MatthieuBonne** [comment]
Just pushed a fix, please tell me if it helps.

**Comment by robgw84** [comment]
I cant tell at the moment because it stopped crashing. It seemed to have stopped after the servers came back up, but I cant tell for sure that is the reason but that seems to be the case.
