### ISSUE TITLE
2 Auction name settings didn't carry over with new build

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#30]
Did CQ take some Heroes off Auction and I missed the post?

![image](https://user-images.githubusercontent.com/9310914/66591529-26fd4b80-eb61-11e9-9e3d-a752077baccf.png)

It's IN the setting file

```
  "bids": [
    {
      "biddingEnabled": false,
      "name": "Kumu-San",
      "maxLevel": 99,
      "maxBid": 1075
    },
    {
      "biddingEnabled": false,
      "name": "Hidoka",
      "maxLevel": 99,
      "maxBid": 1075
    },
    {
      "biddingEnabled": false,
      "name": "Reindeer",
      "maxLevel": 99,
      "maxBid": 1075
    }
  ],

```
But when I loaded up CQA, only Hidoka loaded up. The others aren't even listed in the drop box.

**Comment by Vitae666** [comment]
Reindeer and Kumu-San are def listed in Auction in game. Just checked. Got back from work just a bit ago :)

![image](https://user-images.githubusercontent.com/9310914/66625442-44aecd00-ebc2-11e9-9584-5fa7361632d4.png)![image](https://user-images.githubusercontent.com/9310914/66625483-5bedba80-ebc2-11e9-87ec-19827a8dc281.png)
Don't know why they dropped off the app. Don't even see anything that might show where it happened in the code.
I just downloaded the previous .exe as a test and every single Hero is there.
![image](https://user-images.githubusercontent.com/9310914/66625766-a1f74e00-ebc3-11e9-8ee1-89fa0d73c1ae.png)

**Comment by Vitae666** [comment]
Well.......shit.....
Downloaded latest version again (same one that didn't have all the Heroes), and all of them are there...
The hell?...
You can tell. 1st post's pic, blank. 2nd post's pic, no scroll bar.
Now, the scroll bar is there and Reindeer and Kumu-San are listed in it.
Da'fudge?....

**Comment by MatthieuBonne** [comment]
I think it's due to yesterday's AH bug. ;)

**Comment by Vitae666** [comment]
Wait....the Auction list in CMQ is populated from in game? 
Well, that's kewl. I thought it was coded in like all the other heroes. Didn't know. But does explain it :)
