### ISSUE TITLE
In ErrorLog.txt

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#31]
10/14/2019 7:01:46 PM
	Error JsonParseError Invalid JSON string
10/14/2019 8:40:37 PM
	Error JsonParseError Invalid JSON string

No idea what it's about. I haven't run the CQMC since around 1PM, so it's something with CQA.

**Comment by MatthieuBonne** [comment]
Looks like server sent bad data. Nothing really important, but it can help to spot server failures sometimes.

**Comment by Vitae666** [comment]
Ok, kewl. Thought it was something thrown by CQA :)
