### ISSUE TITLE
Snake

### ISSUE THREAD

**Issue by MrOzzy86** [MatthieuBonne/CQAutomater#32]
Could you please up the minimum for the snake random score submit to like 250?
Half the time i come to use it and I roll 180-200, and I end up having to play it as normal.
I know you don't want to auto-give top scores to everyone, but 180 floor is pretty low.
Thanks.

**Comment by MatthieuBonne** [comment]
Won't Gaia react badly if CQA always gives better scores to its users than other players ?
I don't mind doing a 200-250 pick instead of 180-270... But 250 minimum seems very unfair to real snake users.

**Comment by MatthieuBonne** [comment]
Next update will be 200-315.
