### ISSUE TITLE
AH not updating UM on Refresh again (still?)

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#34]
So, had some spare UM and did some auctions. Won my final one, and after 30 mins or so, noticed that I still had 504 and 261 in game.
Figured I'd record it before I checked to see if unchecking/checking Enable Auto-Leveling fixed it like it usually does. Of course it did :)
[http://youtu.be/Bsq9yoJPoEg?hd=1](http://youtu.be/Bsq9yoJPoEg?hd=1)

**Comment by Vitae666** [comment]
Sadly, this is still an issue so I keep losing auctions. :sob: 
![image](https://user-images.githubusercontent.com/9310914/89148459-e7f11a00-d527-11ea-84ed-84bc6b748996.png)
![image](https://user-images.githubusercontent.com/9310914/89148498-01926180-d528-11ea-8a7c-25198b420b51.png)

**Comment by MatthieuBonne** [comment]
I added a getCurr in AH module, might help !
