### ISSUE TITLE
Crash at startup (v4.5.0.3)

### ISSUE THREAD

**Issue by LudoKressh** [MatthieuBonne/CQAutomater#35]
"Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.InvalidOperationException: Un objet qui autorise la valeur Null doit posséder une valeur.
   à System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   à System.Nullable`1.get_Value()
   à CQFollowerAutoclaimer.PFStuff.<GetGameData>d__65.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CQFollowerAutoclaimer.Form1.<getData>d__35.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CQFollowerAutoclaimer.Form1.<startTimers>d__33.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)."

**Comment by MatthieuBonne** [comment]
Sorry, my last commit was waiting for my approval and I hadn't checked it...

**Comment by LudoKressh** [comment]
Everything is working as expected !
Thank you.
