### ISSUE TITLE
New Update Crashes

### ISSUE THREAD

**Issue by robgw84** [MatthieuBonne/CQAutomater#36]
Something in the new update is causing the automater to crash. I believe it happens when it tries to use a coupon, because in the error logs I keep seeing this:
31/10/2019 10:54:36 AM
	Error Cloud Script Error: Send coupon (maybe coupon already used) {"ok":false,"err":"You already claimed the coupon"}
And then it crashes after that. Its fine if this happens while I am at my pc, but when it happens while I am asleep or at work it kind of defeats the purpose of the automater.

**Comment by Vitae666** [comment]
I don't think it's related to the coupons. It tries the coupons shortly
after you've started it up as one of the start up procedures. I started it
up at 11:48AM and 20 seconds in, I got the Error Log entry of already
trying it.

What it is is that there is a load of server errors thanks to the Halloween
event and calc users.
When I try to get the Event Lineup I'll get the
   Unexpected character encountered while parsing value: D. Path '', line
0, position 0.
error which at this point I am 100% certain has nothing to do with
Automater or Creator like I used to think. It's something on the server
side that causes it.
When I try to use the Creator, it'll throw errors saying that the solution
was rejected 3 times, and I'll have to run it up to 4 times before it's
accepted.

Basically, when CQA gets a Server Error of some sort, it sends it into a
tailspin and it crashes.

10/31/2019 3:34:31 AM Error in PFStuff The remote server returned an error:
(503) Server Unavailable.
10/31/2019 3:35:40 AM Error in PFStuff The operation has timed out
10/31/2019 3:35:53 AM Error in PFStuff The operation has timed out
10/31/2019 3:36:00 AM Error in PFStuff The operation has timed out
10/31/2019 3:36:19 AM Error in PFStuff The operation has timed out
10/31/2019 3:36:44 AM Error in PFStuff The operation has timed out
10/31/2019 3:36:51 AM Error in PFStuff The operation has timed out
10/31/2019 3:37:17 AM Error in PFStuff The operation has timed out
10/31/2019 3:37:27 AM Error in PFStuff The operation has timed out
10/31/2019 3:37:48 AM Error in PFStuff The operation has timed out  -- This
was where I crashed last night
10/31/2019 10:23:29 AM Error in PFStuff The operation has timed out -- When
I woke up
10/31/2019 10:23:29 AM Error in PFStuff The operation has timed out

**Comment by Vitae666** [comment]
Tailspin

10/31/2019 11:50:27 AM
	Error in PFStuff
	Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
10/31/2019 11:50:27 AM
	Error in PFStuff
	Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
10/31/2019 12:08:45 PM
	Error in PFStuff
	The remote server returned an error: (502) Bad Gateway.

![image](https://user-images.githubusercontent.com/9310914/67965270-21cb7380-fbd8-11e9-8d0d-617db5e3e3bf.png)

**Comment by MatthieuBonne** [comment]
Agreed with @Vitae666 : it's due to server fails. Though, CQA shouldn't crash like that. I have to find where in the code I forgot a failsafe...

**Comment by robgw84** [comment]
It doesn't crash right after I start it so its not checking the coupons right away. But there is only one coupon a day so it shouldn't be checking repeatedly.

**Comment by robgw84** [comment]
And its not just because of the event either because the crashes have been happening since the update, not just yesterday when the event started.

**Comment by MatthieuBonne** [comment]
Hmm... Any info in ExceptionLog ?

**Comment by robgw84** [comment]
No the last entry in the ExceptionLog was from the 13th.

**Comment by Vitae666** [comment]
It checks coupons once everytime you start up CQA. About 20 seconds in. 
Unknown when it checks again, But I'd assume it's on a set schedule of several hours unless coupons are always posted at the exact same time every day. Doubt it's slamming Twitter repeatedly.
Either way, I'm willing to bet this has nothing to do with coupons, but everything to do with the server issues. 
But what do I know :)

Nothing's been in the ExceptionLog in a long time. No crashes are being reported in there.

**Comment by robgw84** [comment]
I guess I am going to have to watch the time when I next restart it and keep track of when it crashes so I can show you that its not checking coupons right away after starting. Every single time it crashes for me a coupon error shows up in the ErrorLog, currently its been about 10 minutes since the last crash and I restarted it right after it crashed. If it checks coupons immediately then there is no need to do so in like 20 minutes later.

And I Vitae666 I am going to say it again, this crashing was happening before the Halloween event, so it is not just the server being overloaded. It is happening more often now during the event, but it was happening at least once or twice a day before it.

**Comment by Vitae666** [comment]
ActionLog
**10/31/2019 12:17:00 PM  **-- Restart**
	 Sending coupon 0MZ9A4yABN
10/31/2019 12:25:15 PM
	Error in PFStuff
	Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
10/31/2019 12:28:59 PM
	Error in PFStuff
	Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
10/31/2019 12:29:00 PM
	Error in PFStuff
	Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
10/31/2019 12:29:53 PM
	 Sending coupon 0MZ9A4yABN
10/31/2019 12:41:40 PM
	Error in PFStuff
	Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
**10/31/2019 12:50:51 PM **-- Crash**
	Error in PFStuff
	The remote server returned an error: (502) Bad Gateway.

ErrorLog
**10/31/2019 12:29:59 PM  -- Restart**
	Error Cloud Script Error: Send coupon (maybe coupon already used) {"ok":false,"err":"You already claimed the coupon"}

I do note that it took 13 minutes for the coupon error, but there was another 21 minutes before it crashed.

**Comment by Vitae666** [comment]
Also, this is what I'm meaning with weird server errors

Successfully got enemy lineup for Halloween108 - EVENT,F9,F28,W26,E31,W28
Waiting 2.85 s to send solution
Solution rejected by server
Attempt no. 2 in 5 seconds
Solution rejected by server
Attempt no. 3 in 5 seconds
Solution rejected by server
Solution invalid, solving was stopped
Successfully got enemy lineup for Halloween109 - EVENT,E27,A26,W6,F21,A20

My solution for 108 was rejected 3 times, BUT it still went thru. Doesn't always happen. I've clicked Event Lineup everytime after the errors and 9 out of 10 it's still the one that was rejected and then it magically is the new one (108/108/108/108/109)

**Comment by Vitae666** [comment]
Successfully got enemy lineup for Halloween108 - EVENT,F9,F28,W26,E31,W28
Waiting 2.85 s to send solution
Solution rejected by server
Attempt no. 2 in 5 seconds
Solution rejected by server
Attempt no. 3 in 5 seconds
Solution rejected by server
Solution invalid, solving was stopped
Successfully got enemy lineup for Halloween109 - EVENT,E27,A26,W6,F21,A20
Attempt no. 2 in 5 seconds
Solution rejected by server
Attempt no. 3 in 5 seconds
Solution rejected by server
Solution invalid, solving was stopped
Successfully got enemy lineup for Halloween109 - EVENT,E27,A26,W6,F21,A20
Solution rejected by server
Attempt no. 2 in 5 seconds
Solution rejected by server
Attempt no. 3 in 5 seconds
Solution rejected by server
Solution invalid, solving was stopped
Successfully got enemy lineup for Halloween109 - EVENT,E27,A26,W6,F21,A20
Solution rejected by server
Attempt no. 2 in 5 seconds
Solution rejected by server
Attempt no. 3 in 5 seconds
Solution rejected by server
Solution invalid, solving was stopped
Successfully got enemy lineup for Halloween109 - EVENT,E27,A26,W6,F21,A20
Solution rejected by server
Attempt no. 2 in 5 seconds
Solution rejected by server
Attempt no. 3 in 5 seconds
Solution rejected by server
Solution invalid, solving was stopped
Successfully got enemy lineup for Halloween109 - EVENT,E27,A26,W6,F21,A20
Solution rejected by server
Attempt no. 2 in 5 seconds
Solution rejected by server
Attempt no. 3 in 5 seconds
Solution rejected by server
Solution invalid, solving was stopped
Successfully got enemy lineup for Halloween110 - EVENT,W2,E17,W31,W21,F17,A18

**Comment by Vitae666** [comment]
And the D error I mentioned when trying to get the event line up

************** Exception Text **************
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at CQMacroCreator.PFStuff.getHalloweenData(String id)
   at CQMacroCreator.Form1.getHalloweenButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

BTW, I do realize that my posts have nothing to do with CQA or Matt's version of CQMC and is all about Ayla's CQ and CQA.
Just trying to get my point across that there's a shit ton of crap on the server right now that is causing errors.
And yeah, I know that it was happening yesterday before the event started. But their, possibly, poorly setup server for this event, was likely in place and it's, possibly, doing weird crap with the main server which is causing CQA to get weird.
And yeah, CQA crashes on the occasion, but it hasn't done it, at least for me, **for days** since yesterday.

**Comment by robgw84** [comment]
Vitae666, the program was updated 4 days ago... The crashes started then, not yesterday.
Also the last stuff you posted there is not server stuff, its an issue with code within the macro creator.
