### ISSUE TITLE
Settings not saving Adv and Lottery settings

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#38]
Had Adv set to AS and Lottery to 1, but it's not saved in Settings.json

**Comment by MatthieuBonne** [comment]
Yep, aware of this missing feature, but currently too busy irl. ^^ I'll do it asap.

**Comment by Vitae666** [comment]
👍

**Comment by MatthieuBonne** [comment]
Done in the upcoming 4.5.0.7 !

**Comment by Vitae666** [comment]
Weird...Everytime I restart CQA the # of lottery tickets I want is reset in the setting.json file, but not before it's loaded with the correct #. Like, I'll have 1. Close. Open. CQA says 1. Settings says 0. 
And the only way to save the # is by turning Lottery off and on. 
All documented here:
http://youtu.be/ya3Ln8p1lAs?hd=1

Left off the part where when I close CQA with the setting saying 0 that it loads with 0 in CQA, but figured that went without saying :)

**Comment by MatthieuBonne** [comment]
I see where it comes from, will fix asap. Thanks.

**Comment by Vitae666** [comment]
"optAutoAD": 0,
  "doAutoLO": true,
  "optAutoLO": 0

The Lotto ticket amount in Settings is still being reset to 0 when restarting the Automater so that a 2nd restart puts it at 0 in the UI but is 1 the 1st time.

**Comment by MatthieuBonne** [comment]
Should work better now ! :)
