### ISSUE TITLE
Question not related to CQAutomater

### ISSUE THREAD

**Issue by mcoval** [MatthieuBonne/CQAutomater#39]
Hi,
Sorry for asking there, but i dont know any other place where someone will know how to help me.
I plan to make a tournament best lineups history.
I get data from http://cosmosquest.net/tdata.php?id=597
every player setup are contained in array format like:
setup: "[-67,-76,-131,-110,-143,-148,-35,-56,-137,-27,-45,-144,-39,-48,51,50,51,45,-115,-117,-107,-3,-62,-87,35,29,-1,-1,-1,-1]"
My question is - how to decode that numbers to heroes/monster names and promotions? Mayby 
Thanks for any kind of help :)

**Comment by MatthieuBonne** [comment]
Hi ! It'd be great to make this project happen. :)
You can find heroes' ordered list here : https://github.com/MatthieuBonne/CQAutomater/blob/master/CQFollowerAutoclaimer/Constants.cs (-2 = lot, -3 = tiny, etc)
How do you plan to code this ? I've been thinking about grouping existing tools (CQA, gsheets...) on a shared database to reduce server calls, I'm currently lacking time to do it myself but always willing to share ideas !

**Comment by mcoval** [comment]
There is no way to do this ;/ That site (http://cosmosquest.net/tdata.php?id=666) contains only info about setup (used monsters and heroes) but without their lvl and promotions ;/

**Comment by MatthieuBonne** [comment]
Well, we CAN do this, if we store PvP history from CQA users in a shared database. That's precisely where I'm going, but I'll need a few weeks to get it done, too much rl work currently. :)

**Comment by MatthieuBonne** [comment]
This is under work ; for now I store pvp fights and tournament grids, it works pretty well. I'll show the output soon.

**Comment by MatthieuBonne** [comment]
I'd like some beta testers for the new features, just players running latest CQA so the database can grow. @mcoval ? @Vitae666 ? @Cirkulis ? @LudoKressh ?

**Comment by LudoKressh** [comment]
update done and option enabled.

**Comment by mcoval** [comment]
update done, whitch option i need to enable ?

**Comment by LudoKressh** [comment]
Enable PvP history on the PvP tab.

**Comment by Vitae666** [comment]
Just saw this. Will be home in about 10hrs. Will enable then.

**Comment by MatthieuBonne** [comment]
Thank you all. Please report crashes if some happen, I'll monitor the data and tell you if some update is needed. :)

**Comment by MatthieuBonne** [comment]
New version committed, to fix some small stuff but mostly to save up-to-date pvp grids. Please update asap.
Preview of output : http://dcouv.fr/cq.php?p=734
Please, please don't share the link for now, I haven't secured everything. I'll add a password if there are too many visits.

**Comment by LudoKressh** [comment]
update done

**Comment by LudoKressh** [comment]
Somrthing strange with PvP weekly statistics :
> Lane efficiency : 1 (0.6066), 5 (0.5130), 4 (0.0201), 6 (0.0087), 3 (**-0.1111**), 2 (**-0.9811**)

**Comment by MatthieuBonne** [comment]
Looks ok to me, -1 means 100% losses, 1 means 100% wins. You seem to have 2 strong lanes and one suicide. Is that incorrect ?

**Comment by MatthieuBonne** [comment]
(I'll have to improve this display obviously ! ^^)

**Comment by LudoKressh** [comment]
For me, a efficiency is between 0 (no win) and 1 (all won).

**Comment by Vitae666** [comment]
I tried checking that page out but it won't load for me.
Have only checked on my phone so far.

**Comment by Vitae666** [comment]
![Screenshot_20191205-205606](https://user-images.githubusercontent.com/9310914/70289434-c24a2000-17a2-11ea-95c2-fb9f74b30d2d.png)

**Comment by MatthieuBonne** [comment]
Quickly fixed a few bugs when I could, including the efficiency display. Any feedback ?
I'm trying to end my current business projects before 31/12, then I'll add some improvements. In CQA I want to do something with EAS day (an option to force a hit on each EAS boss), and in the web stuff I'm thinking about more cron jobs to run, to analyze data and help us build better grids.

**Comment by LudoKressh** [comment]
The efficiency display is better to me. It's more understandable to have something between 0 and 1.
In CQA, a "Hit Now" button on the "World Boss" tab could be useful.
I am impatient to see the new features you are going to add.

**Comment by MatthieuBonne** [comment]
I'm adding features on the web interface, should be useful for tournaments.

**Comment by MatthieuBonne** [comment]
Flash history in beta-test ; only works for FT in which a CQA user entered.

**Comment by LudoKressh** [comment]
Update done.

**Comment by LudoKressh** [comment]
you've blocked access to certain features.
Any new features coming?

**Comment by MatthieuBonne** [comment]
It's open again. I was trying to develop some kind of a falsh calc but results are poor (just look at my latest scores ^^) ; I disabled it for now. Maybe someone with coding skills will help ?
I plan on improving the units tab by changing the second hero table (with +10/+10 bonus) so that it calculates a max bonus from the hero list. If you have other requests or suggestions, shoot ! :)

**Comment by MatthieuBonne** [comment]
I added a way to sync p6 data with one's hero pool : try the link at the end of your player page. Hero pool fills from PvP fights so it may take a few days to be accurate, but at least we have a way to check which p6 are done and which we can do next !
