### ISSUE TITLE
Emily question

### ISSUE THREAD

**Issue by Cirkulis** [MatthieuBonne/CQAutomater#40]
Hi, for some reason SUPER KRYTON Heroes Allowed fought with: emily:99 neil:99 mother:99 aauri:99 aathos:99 ageum:99 did only 137.613.218.743.340 dmg instead of expected 3.223.672.216.726.598. Looks like Emily was ignored or replaced with some other hero or something. Could you look into this?

**Comment by MatthieuBonne** [comment]
Same issue here, trying to find why.

**Comment by MatthieuBonne** [comment]
Fixed.
