### ISSUE TITLE
Can't Level Adam :-/

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#41]
Says he's lvl 1 when he's 14.
![image](https://user-images.githubusercontent.com/9310914/69214574-4f4f7100-0b35-11ea-9214-aaeabde8e292.png)

ErrorLog
11/20/2019 1:27:21 AM
11/20/2019 1:27:24 AM
	Error Cloud Script Error: level super {"ok":false,"err":"Only Super Heroes"}
11/20/2019 1:27:25 AM
11/20/2019 1:27:28 AM
	Error Cloud Script Error: level super {"ok":false,"err":"Only Super Heroes"}
11/20/2019 1:27:29 AM

EDIT: Also, just in case, I also unchecked/checked the Enable Auto-Leveling box to see if it would refresh. Nope :)

**Comment by MatthieuBonne** [comment]
Thanks, it'll be fixed in next commit.

**Comment by Vitae666** [comment]
Ok, I'm thinking there's something wrong with the order or something.
Tried to level Emily and it leveled Adrian.
In game Casper says it's lvl 1. CQA says it's lvl 0.
In game Adrian says it's lvl 8. CQA says it's lvl 1.
In game Emily says it's lvl 2. CQA says it's lvl 8.
In game Adam says it's lvl 39. CQA says it's lvl 2.

**Comment by MatthieuBonne** [comment]
Please try latest exe.

**Comment by Vitae666** [comment]
Going to get the new version now.
