### ISSUE TITLE
Leveller didn't respect AS limit

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#43]
I keep having the problem where the levels and currency aren't being updated unless I Disable/Enable Auto-leveling, and for some reason it didn't keep 100 in the bank. Confirmed visually in game.
I don't know if it was BECAUSE it doesn't show the update that Disabling/Enabling it constantly, it pushed it over. I had to do it 5 times because it wasn't fully leveling Arie up. It would do a few levels and then stop. Like it would do 2 levels and stop. It was doing the same with Ashygu. I had enough to get to lvl 83, but it wouldn't do more than a few levels (<10 at a time sometimes) So I just kept dis/en and only noticed afterwards that all my AS was used up for some reason.

![image](https://user-images.githubusercontent.com/9310914/73384333-105a3c00-4299-11ea-8a32-df148e58307a.png)

**Comment by MatthieuBonne** [comment]
Hmm. I reduced the timer interval on autolevel, it was strangely high. Tell me if it helps.

**Comment by Vitae666** [comment]
Meant to close this a while ago

**Comment by Vitae666** [comment]
Temporarily opening this up again.
![image](https://user-images.githubusercontent.com/9310914/82164936-147a8b80-9881-11ea-9eb7-970dcb2429c6.png)
Since I only have 1 AS and 1 CC Adventure listed, I'm pretty sure that I'm still on the 3rd one (there ARE 3 right?!) 
I was paying so much focus to the Save and DQ updates that I wasn't paying attention to Adv. and was removing stuff (Hero levelling, etc) from the ActionLog unrelated to the DQ errors so I could post them.
BUT this does show that it's still sending me on Adventures other than the one that is requested. There should be an Update Currencies sent before you go on an Adv. with a small time delay of 30(? or whatever time it takes for CQA to recieve the update) seconds so that the correct amount is known by CQA to send you on the right one :(
![image](https://user-images.githubusercontent.com/9310914/82165079-af736580-9881-11ea-8c3a-b4f101895438.png)

**Comment by Vitae666** [comment]
WHEW! Ok, was on the last adventure. But the whole doing the wrong one still stands :)

**Comment by MatthieuBonne** [comment]
Ok it'll be fixed in next commit (after this event).
