### ISSUE TITLE
Auction timers don't understand 24hrs+

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#44]
![image](https://user-images.githubusercontent.com/9310914/74097544-02978880-4adb-11ea-9afb-3f1456741e3e.png)
![image](https://user-images.githubusercontent.com/9310914/74097558-3ecae900-4adb-11ea-815c-9a5a46c803b5.png)
Not that I'm even remotely going to ever bid, much less win, them. Was something I noticed.

**Comment by Vitae666** [comment]
Also, side problem, but related to Auction
2/9/2020 10:04:32 PM
	FAILED Bid on hero Pokerface for: 243UM.
**{"ok":false,"err":"Unknown hero"}**
2/9/2020 10:04:36 PM
	FAILED Bid on hero Pokerface for: 243UM.
**{"ok":false,"err":"Unknown hero"}**

FML: And now, 24hrs later, it worked fine.

**Comment by MatthieuBonne** [comment]
Bug 1 solved ; bug 2 : uh ? Guess it was a server issue. ^^

**Comment by Vitae666** [comment]
Not sure if this is related to the fix, but...I just updated yesterday and umm....check the "ends in"
![image](https://user-images.githubusercontent.com/9310914/74628856-b2e13e80-5124-11ea-9bfb-22dc28a7c0cc.png)
I've restarted CQA a few times just to see.

**Comment by Vitae666** [comment]
Added interesting note:
I disabled all of them, unchecked/checked "Enable Auto-Leveling" because for some reason I have less than 100 AS in the bank again (no, not on an Adventure either) and the levels adjusted. I didn't even notice that I had more than 1 level of each. 
![image](https://user-images.githubusercontent.com/9310914/74631233-73b5ec00-512a-11ea-9017-7f47a952036c.png)
Visually confirmed in game as well.

**Comment by Vitae666** [comment]
Current version and "Ends in" is still screwed :(
![image](https://user-images.githubusercontent.com/9310914/75421316-fa777f80-5907-11ea-8bc6-282bbcce87af.png)

**Comment by MatthieuBonne** [comment]
Hmm, better with today's version ?

**Comment by Vitae666** [comment]
Internet's down so can't check. Will when able

**Comment by Vitae666** [comment]
Yeap. End timer fixed.

**Comment by Vitae666** [comment]
Ok, soooooo.....Soon as I started up the update i've been getting in my ActionLog
2/27/2020 7:34:20 PM	Specified cast is not valid.
2/27/2020 7:34:30 PM	Specified cast is not valid.
2/27/2020 7:34:31 PM	Specified cast is not valid.
....
2/27/2020 9:28:59 PM	Specified cast is not valid.
2/27/2020 9:29:05 PM	Specified cast is not valid.

**Comment by MatthieuBonne** [comment]
Fixed.
