### ISSUE TITLE
3 small PFStuff edits & 1 AutoChests for visual aesthetics in ActionLog

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#46]
Damned if I know how to do a pull request or whatever it's called, for changes without making my own fork,
**_PFStuff:_**
Line 1411:
                        + " 10 times with: " + mode);
Line 1442:
                        + " with: " + mode);

Just to add spaces. Used to look like
                        + "10 times with: " + mode);
                        + "with:" + mode);
And the output was:
	Leveled up hero: Areiwith:AS

1379 was correct :)

**_AutoChests:_**
Line 55
                    rew += PFStuff.chestResult < 0 ? Constants.heroNames[-PFStuff.chestResult] : Constants.rewardNames[PFStuff.chestResult] + " from " + mode + " chest";

So it looks like
Got 50 UM from normal chest

I would have liked to add DateTime.Now to JUST the Log, but I couldn't figure out which one was the UI screen display and which the actual writing to the file. Or if there was even a difference, so I gave up that part :)

**Comment by MatthieuBonne** [comment]
Thanks, it'll be included in next commit (coming today). :)
