### ISSUE TITLE
Not so damned Rare now, but have had DQ's not start at all

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#50]
Talking maybe max 2 to 3 times a month where DQ's timer reset to the next "day" and it's hours into it, but CQA hasn't kicked in.
There's nothing in the logs either to show what happened.
I mean, I get a LOT of errors in there that I assume are pretty much just cause my internet sucks (f'ing AT&T)

ActionLog:
4/13/2021 11:21:01 AM
	Error in PFStuff
	The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
4/13/2020 11:18:53 PM
	Error in PFStuff
	The operation has timed out
4/14/2020 8:53:25 AM
	Object reference not set to an instance of an object. **I get this one A LOT**
4/9/2020 9:08:05 PM
	Error in PFStuff
	Unable to connect to the remote server
4/4/2020 3:44:16 PM
	This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse

ErrorLog:
3/25/2020 8:42:40 AM
	Error JsonParseError Invalid JSON string
3/25/2020 11:19:16 AM
	Error ConnectionError A task was canceled.
3/28/2020 5:15:59 AM
	Error DownstreamServiceUnavailable A third-party downstream provider returned an error to 
4/2/2020 6:53:36 PM
	Error InternalServerError An unexpected error occured while processing the request.

With all of these going off at random times and multiple times and multiple of them all at once, I can't tell which one, if any of them, happen to go off when DQ doesn't start.

I'm going on my own assumption here, but when DQ's daily timer ticks over, I know you must do a ping, or whatever you techies would call it, and start doing DQ's. 
But what if there's one of those errors. Maybe the "Unable to connect to remote server" one? Do you have CQA wait a few mins and try again and again until it gets a ping back?

Hell, I don't even know if any of those errors are even yours. The word "occurred" is spelt "occured" in the last error and "occured" isn't even a word in your files. I did a search :)

Or maybe CQMC misfired and the DQ's didn't start and didn't get rechecked? 
I have this in CQMCErrors, BUT I don't know if it's the day DQ's didn't start. I think it was, but really not sure.

4/12/2020 9:58:49 PM

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CQMacroCreator.Form1.setDQData()
   at CQMacroCreator.Form1.runCalcButton_Click(Object sender, EventArgs e)
   at CQMacroCreator.Form1.sendTillNoSolveButton_Click(Object sender, EventArgs e)
   at CQMacroCreator.Form1..ctor()
   at CQMacroCreator.Program.Main()

Unhandled Exception: OutOfMemoryException.

**Comment by MatthieuBonne** [comment]
Have you updated CQMC ? My guess would be that you've met a DQ with new heroes...

> Do you have CQA wait a few mins and try again and again until it gets a ping back?
Hmm, nope.

**Comment by Vitae666** [comment]
Always have new versions. And a few times I've opened up CQMC to see what
I'm up against, and it's just monsters and old heroes.
Would it be possible to have it ping every 10 mins or so if the DQ = 1 and
stop the ping if it's > 1?
And by ping I mean whatever it is that happens that CQA does when it rolls
over to 1 for the new day :)

**Comment by MatthieuBonne** [comment]
Ok, added something like that in next commit.

**Comment by Vitae666** [comment]
Ok, I know you added the new commit, and I'll get that one. Just wanted the visual proof that I'm not nuts :)
From what I can tell, the ActionLog doesn't indicated what's wrong because it's showing data 2hrs old and the new DQ started less than an hour ago. There was no recent entry in the other logs. So, I have no idea what happens that it doesn't initiate at times.
BUT here it is. Now, I'll download the latest.
![image](https://user-images.githubusercontent.com/9310914/79590615-468fa680-80a5-11ea-9a6b-165b11a28240.png)

**Comment by Vitae666** [comment]
With the new commit.
Soon as I started it up, and it started running the DQ, there was a crash with CQMC.

CQMCErrors

> 4/17/2020 12:37:32 PM
> AutoDQ error received from calc
> 
> AutoDQ error received from calc
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
> AutoDQ error received from calc
>    at CQMacroCreator.PFStuff.sendDQSolution()
> AutoDQ error received from calc
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
> AutoDQ error received from calc
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> AutoDQ error received from calc
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> AutoDQ error received from calc
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> AutoDQ error received from calc
>    at System.Threading.ThreadHelper.ThreadStart()

Exceptionlog

> 4/17/2020 12:37:48 PM
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at CQMacroCreator.PFStuff.sendDQSolution()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()


EDIT: Oh wait...it says the CQMC error came from the calc. Worked the 2nd time, so guess it just pitched a quick fit.

**Comment by MatthieuBonne** [comment]
Yes, the error comes from the calc, if you find what it is it could be interesting.
I'm trying to prevent CQA crashes in that situation anyway ! ^^

**Comment by Vitae666** [comment]
Welp...No crash to stop it this time. :(
![image](https://user-images.githubusercontent.com/9310914/79895463-eb2b2480-83d4-11ea-944d-afdca5d6e64a.png)

**Comment by MatthieuBonne** [comment]
Does the bug happen if you uncheck calc box ?

**Comment by Vitae666** [comment]
Will have to see on the next go around. Happened again today :(

![image](https://user-images.githubusercontent.com/9310914/80060882-aa7afa80-84fd-11ea-90df-5ed6cb9e0b2c.png)

Unchecked the Run the Calc.

**Comment by Vitae666** [comment]
hrmm...I'm wondering...Maybe it's not running when there's new versions of CQMC and I haven't run then to be able to uncheck the checkbox regarding always running?
If that's the case, it would be a new thing. It's run before. Hell, once it went for 2 weeks before I needed to check CQMC and discovered I hadn't run it or the Calc on it's own.

**Comment by Vitae666** [comment]
> hrmm...I'm wondering...Maybe it's not running when there's new versions of CQMC and I haven't run then to be able to uncheck the checkbox regarding always running?
> If that's the case, it would be a new thing. It's run before. Hell, once it went for 2 weeks before I needed to check CQMC and discovered I hadn't run it or the Calc on it's own.

Meant to post a few days ago. It happened again, it was 4hrs into DQ and it hadn't started running.
100% certainty that CQMC and the Calc were, while new, were opened and run and told to always run, the day before.
I was about to screenshot it and post and then *boom* crashed due to the PVP issue.
Like I'd mentioned above, I've had CQA run with versions of CQMC and Calc both being new and never opened with out a problem several times before. And it was maybe at most 3 times a month. But so far it's more like in the 2 weeks since I let you know, it's been about 3 or 4 times.
I'd forgotten to uncheck the "Run Calc" like you suggested. I've done it now. It's so intermittent, that I wouldn't know if that helped or not for sure :)

**Comment by Vitae666** [comment]
Interesting note: If you have "Run the calc" unchecked, and later click "Run calc now" want to guess what won't run?
If you said "Calc" or "CQMC" you'd be correct :)

3.5hrs into the new DQ phase, "Using Best Lineup" is still displayed for some reason.
Click "Run calc now" and nothing happens for several minutes. Click it again, cause I don't trust myself anymore at this point. Still nothing.
Check off "Run the calc" and get the "do you want to run the calc" question. I click "Yes" duh. And it runs.
After it's run out of things that it can kill, I kill CQMC so it will stop running (BTW, did you notice my idea about adding a setting to the Settings.json for the CQMC Timer so that it will interact with CQA? Alya said "nope" boooooo!!), uncheck "Run the calc" and for shits and giggles click "Run calc now" and "Using Best Lineup" gets displayed and CQMC never kicks in.
Shouldn't manually clicking "Run Calc now" with "Run the calc" unchecked still activate the CQMC process? Logically, I'd think yes because I'm clicking it to tell it to run :)

**Comment by Vitae666** [comment]
Welp....nope.
![image](https://user-images.githubusercontent.com/9310914/80659417-ee6a8400-8a56-11ea-96d5-69dc5fd0be6f.png)
Nothing in the logs.

**Comment by MatthieuBonne** [comment]
Can you please test with a basic lineup ? (no monsters, no recent heroes)

**Comment by Vitae666** [comment]
Will do. Just got to work.
So basic. Like caveman shaman..the originals. Got it.

**Comment by Vitae666** [comment]
Forgot to change to the basic originals. Ran it (Had come home to it crashed) and got this in the ActionLog

> 5/3/2020 1:00:11 AM
> 	Debug pvp DQFailedAttempts = 0
> 5/3/2020 1:01:22 AM
> 	Debug pvp DQFailedAttempts = 0
> 5/3/2020 1:02:20 AM
> 	Object reference not set to an instance of an object.
> 5/3/2020 1:02:53 AM
> 	Object reference not set to an instance of an object.
> 5/3/2020 1:04:39 AM
> 	Debug pvp DQFailedAttempts = 0
> 5/3/2020 1:04:45 AM
> 	Debug pvp DQFailedAttempts = 0
> 5/3/2020 1:04:51 AM
> 	Debug pvp DQFailedAttempts = 0
> 5/3/2020 1:04:57 AM
> 	Debug pvp DQFailedAttempts = 0
> 5/3/2020 1:05:09 AM
> 	Debug pvp DQFailedAttempts = 0
> 5/3/2020 1:05:15 AM
> 	Debug pvp DQFailedAttempts = 0
> 5/3/2020 1:05:21 AM
> 	Debug pvp DQFailedAttempts = 0
> 5/3/2020 1:14:03 AM
> 	Debug pvp DQFailedAttempts = 0
> 

The 1st 2 DQFailedAttempts actually crashed. The others were fine and didn't crash. Dunno why they crashed, but it was on 21 and 41.
Changed it to the OG's, and tried again, and got the DQFailedAttempts msg as well. Will leave them up to see how it goes with the not starting DQ's.

NOTE: the DQFA popped up also when I started the Dung.

Tho, now that I actually read that msg, hecks it saying pvp in it? :)

**Comment by MatthieuBonne** [comment]
Ok ; adding more debug to next commit :)

**Comment by Vitae666** [comment]
Nothing in ActionLog

5/4/2020 5:16:19 PM
	Leveled up hero: Retia with: AS
5/5/2020 12:42:04 AM
	An error occurred while sending the request.

Nothing in ErrorLog
5/4/2020 4:54:52 PM
	Error Cloud Script Error: bid {"ok":false,"err":"Bid desync 221 200"}
5/5/2020 6:36:03 AM
5/5/2020 6:36:09 AM
	Error Cloud Script Error: bid {"ok":false,"err":"Bid desync 700 636"}

Shoulda started at close to 7PM EST yesterday, right?

![image](https://user-images.githubusercontent.com/9310914/81111934-da59d300-8eeb-11ea-8638-b827598ab73d.png)

**Comment by Vitae666** [comment]
Also, I remebered that you'd mentioned seeing if it worked with "Run the calc" unchecked...happened again. Seems to be happening more and more often now :(

All I got is
5/5/2020 6:30:37 PM
	Object reference not set to an instance of an object.
5/5/2020 7:30:12 PM
	Object reference not set to an instance of an object.
5/5/2020 7:49:28 PM
	Object reference not set to an instance of an object.

![image](https://user-images.githubusercontent.com/9310914/81138737-08add180-8f31-11ea-85b6-260f2afd5365.png)

**Comment by Vitae666** [comment]
Decided to test to see if maybe the Best Lineup running was part of the problem....nooope....And not a thing in Logs.
The hell? :(
![image](https://user-images.githubusercontent.com/9310914/81491162-b3d3c900-9258-11ea-84cf-3ebbb66fe745.png)


Also, interesting note.....
![image](https://user-images.githubusercontent.com/9310914/81491465-e8e21a80-925c-11ea-8072-1e16546baed3.png)
Kinda goes along with my post from 11ish days ago about having Run Calc unchecked and then clicking Run calc now not doing anything.

**Comment by Vitae666** [comment]
Been a while, at least that I can remember, but happened again. Got back from work and DQ never started.

Nothing in ErrorLog. And this was in ActionLog, but since it should have gone off around 2:30, it's not much help.
```
6/26/2020 4:26:08 AM
	MOTHER OF ALL KODAMAS No Heroes fought with: F34 F34 F34 F34 F32 F31
6/26/2020 7:00:52 AM
	Object reference not set to an instance of an object.
6/26/2020 7:03:08 AM
	Object reference not set to an instance of an object.
6/26/2020 7:52:05 AM
	Object reference not set to an instance of an object.
6/26/2020 8:00:29 AM
	Object reference not set to an instance of an object.
6/26/2020 8:02:33 AM
	Object reference not set to an instance of an object.
6/26/2020 8:55:49 AM
	Object reference not set to an instance of an object.
6/26/2020 8:59:53 AM
	Object reference not set to an instance of an object.
6/26/2020 9:04:08 AM
	Object reference not set to an instance of an object.
6/26/2020 9:59:09 AM
	Object reference not set to an instance of an object.
6/26/2020 10:03:23 AM
	Object reference not set to an instance of an object.
6/26/2020 11:00:24 AM
	Object reference not set to an instance of an object.
6/26/2020 11:02:27 AM
	Object reference not set to an instance of an object.
6/26/2020 11:16:47 AM
	Object reference not set to an instance of an object.
6/26/2020 11:59:36 AM
	Object reference not set to an instance of an object.
6/26/2020 12:03:41 PM
	Object reference not set to an instance of an object.
6/26/2020 12:58:39 PM
	Object reference not set to an instance of an object.
6/26/2020 1:02:42 PM
	Object reference not set to an instance of an object.
6/26/2020 2:00:01 PM
	Object reference not set to an instance of an object.
6/26/2020 2:04:08 PM
	Object reference not set to an instance of an object.
6/26/2020 2:59:12 PM
	Object reference not set to an instance of an object.
6/26/2020 8:02:18 PM
	 Picking LF cell 4
```

**Comment by Vitae666** [comment]
> Interesting note: If you have "Run the calc" unchecked, and later click "Run calc now" want to guess what won't run?
> If you said "Calc" or "CQMC" you'd be correct :)
> 
> 3.5hrs into the new DQ phase, "Using Best Lineup" is still displayed for some reason.
> Click "Run calc now" and nothing happens for several minutes. Click it again, cause I don't trust myself anymore at this point. Still nothing.
> Check off "Run the calc" and get the "do you want to run the calc" question. I click "Yes" duh. And it runs.
> After it's run out of things that it can kill, I kill CQMC so it will stop running (BTW, did you notice my idea about adding a setting to the Settings.json for the CQMC Timer so that it will interact with CQA? Alya said "nope" boooooo!!), uncheck "Run the calc" and for shits and giggles click "Run calc now" and "Using Best Lineup" gets displayed and CQMC never kicks in.
> Shouldn't manually clicking "Run Calc now" with "Run the calc" unchecked still activate the CQMC process? Logically, I'd think yes because I'm clicking it to tell it to run :)

This odd thing is still happening. I had unchecked it so that while at work I didn't get 10 question boxes asking if I wanted to run DQ with more than 20 heroes (I'm on Alya's updated version). Came back home, clicked "Run calc now" and it just sat on "Using Best Lineup"
Was going to write another post saying something was wrong, but then remembered this.
