### ISSUE TITLE
Am I the only one who wonders...

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#51]
If we are outbidding each other on Auctions? :)

**Comment by MatthieuBonne** [comment]
CQA users are definitely outbidding each other, yeah ; why ?

**Comment by Vitae666** [comment]
No particular reason. Just something I was chuckling to myself about the
other day.
I'm like 3. 2. Dammit!.....4. 3. Dammit!...1. 0. -1. WOOHOO!! -2. DAMMIT!!!
LOL

**Comment by MatthieuBonne** [comment]
:smile:
