### ISSUE TITLE
Lots of stuff filling up the logs with debug info

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#54]
[ErrorLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4506158/ErrorLog.txt)
The ErrorLog is going like that due to CQA crashes that I miss for hours and then it playing PVP catch up. Loads of attempts on the same people. I'm thinking that it's clicking the same 1 person that it's found. And the only reason it moves to another player is that after a minute or so, the leaderboard refreshes and has a new list and then it issues the new attack and then goes back to trying to slam the new opponent over and over. Might need a timer on there between the extra attacks. Maybe something on the info box saying what it's doing?

> Win vs facucomba, ELO +17, Star Dust +1616
> Extra Attacks Left: 3 (Waiting for LeaderBoard Refresh)
> .
> .
> .
> Extra Attacks Left: 0

And, of course, after there's no Extra's there's no "Extra attacks left" output to the screen with any subsequent attacks.
Wouldn't mind a log of the PVP attacks either. Saw some stuff in the code that was commented out for logging the results, or so I thought. Didn't work when I took out the comments. Dunno why. But then again, it's me :)

[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4506159/ActionLog.txt)
Loads of calls to the LTO

Pretty sure this is you everytime you see a post from me
![image](https://user-images.githubusercontent.com/9310914/79801042-60dab600-832b-11ea-8c37-83d0ced5c161.png)

**Comment by MatthieuBonne** [comment]
I think it'll be fixed in next commit. I also removed lto debug.
LOL for the gif ^^ Nah, devs like when users give feedback. ;)

**Comment by Vitae666** [comment]
Ok. Will see. Cause right now I got about 1.5MB of nothing but
Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}
in my errorlog.  Over 15K entries of it.....Every 4 seconds...
4/23/2020 1:01:27 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}
4/23/2020 1:01:31 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}
4/23/2020 1:01:35 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}
4/23/2020 1:01:39 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}
4/23/2020 1:01:43 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}
4/23/2020 1:01:47 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}

**Comment by Vitae666** [comment]
New version too. But don't think anything was changed there
4/23/2020 1:51:13 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}
4/23/2020 1:51:17 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}
4/23/2020 1:51:21 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}
4/23/2020 1:51:25 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}

Pretty sure Gaia's like 
![image](https://user-images.githubusercontent.com/9310914/79801042-60dab600-832b-11ea-8c37-83d0ced5c161.png)
And I'm betting it can't **_just_** be me!
Unless those errors are just logs that the PVP can't initiate and not actual info from CQ server :)

**Comment by Vitae666** [comment]
HOnestly, I don't think PVP is working...
I started CQA and it did an attack. Did the every 4 seconds log thing until the timer ran down for the next attack and it never did it.
Errorlog has
4/23/2020 2:12:32 AM
	Error ConnectionError A task was canceled.
Which is right about the time that the Auto attack should have went off.

Hell. I disabled Auto-PVP and it's still doing the 4 second logs....Disabled history as well, just in case but no luck.

OK! Solved the constant logs (at least for the next 45 mins....maybe) by rechecking Auto-PVP. It did 2 attacks right away. Tho I still have 5 outstanding ones. And it hasn't done them yet.

**Comment by MatthieuBonne** [comment]
I've added some logging (yessssss more logsssss) because I wonder if CQA tries to make you fight with a player outside your range (which may happen with the new ranking).

**Comment by Vitae666** [comment]
Got the new version. Happened to be 2 mins from the next attack. It did the usual "Start up attack if you can" and then the timer ran negative and never attacked.
![image](https://user-images.githubusercontent.com/9310914/80129012-7be43a80-8564-11ea-9760-6d2001bcdc5a.png)
Disabled/Enabled Auto-PVP. Next attack was done. Timer corrected itself.
Nothing in logs. But I was right about what I said in the previous post. Until the next Attack, there's no logs, and then it fills up again every 4 seconds.
Won't know for this one, because I'm leaving for work in 45 :(
Also, the Extra Attacks isn't kicking in still. I have 6, so I'll burn those in game.
Will see what the logs say when I get home in 12hrs (loooong shift today)

NOTE: I did do the Un/Recheck Auto to do some attacks. They did go off. But never started the auto attacks. Nor logs.

**Comment by Vitae666** [comment]
Ok. So, came back and not a damned thing in the errorlog. No spam. I dunno.
Wondering if the extra attacks are causing the spam. Going to disable them for a bit. By bit, I mean while I sleep. When I wake up and enable it, if the spam starts up, then at least that's narrowed down.

Spam = Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"}

**Comment by Vitae666** [comment]
I have no idea what's going on....I woke up to a counter that said -11+hrs, my attack info screen log was full, my Enable Auto-PVP was OFF. I feel like I had restarted CQA before my test just to make sure that everything was fresh, but at this point, I was tired from a long day so, damned if I know. LOL!
Went into the game, and I have full pending attacks. 
I closed and reopened CQA. Auto-PVP was enabled (I never clicked the Save Settings button) and I've sat thru 10 rotations of a 2 min count down, with no attacks. During which all this started up.
```
4/24/2020 1:19:14 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 64A86F5D40DFF73C
4/24/2020 1:19:18 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 64A86F5D40DFF73C
4/24/2020 1:19:22 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 64A86F5D40DFF73C

```

I unchecked/rechecked Auto and it immediately did 2 attacks, the log entries stopped and now I am -2:45 mins in the countdown.
Unchecked/rechecked Auto again. Countdown fixed itself, no attacks (still have 6 pending) and logs immediately started up again with
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 7A7F11CE487860A1

Cleared attacks in game. Disabled Auto. Logs continue. BACK to work. Will see how it looks in the Info Screen when I get back. Still mentally debating if I'd gone to bed with a cleared screen or not.

Rank 2056 if that helps. I remember you said something about attacking someone I couldn't. There was 1 person on my in game list that when I attacked said "Error: Can't fight" don't know if that's what you meant?

**Comment by Vitae666** [comment]
It crashed at 8:25
4/24/2020 8:25:01 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 7A7F11CE487860A1

This exception was originally thrown at this call stack:
	CQFollowerAutoclaimer.PFStuff.sendPVPFight(int)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	CQFollowerAutoclaimer.AutoPvP.sendFight(int)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	CQFollowerAutoclaimer.TaskQueue.queueTimer_Elapsed(object, System.Timers.ElapsedEventArgs)
	System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync.AnonymousMethod__6_1(object)
    ...
    [Call Stack Truncated]

**Comment by MatthieuBonne** [comment]
Can you please try raising above/below limits to 10 ?

**Comment by Vitae666** [comment]
Disabled autopvp while at work to get spares. Problem with the logs is only
when I have spares. If I 0 out then all is good. Wanted to see before I
went, but of course had 20 mins left on the timer and had to leave.

**Comment by Vitae666** [comment]
![image](https://user-images.githubusercontent.com/9310914/80298456-8a944280-875a-11ea-99a5-cbe828ec0a76.png)


EDIT: Dis/Enabled Auto and the timer fixed itself. Did 1 extra attack. No more.
No error logs yet. Only 51 minutes until Countdown reset. Will advise after.

**Comment by Vitae666** [comment]
It did 3 attacks from a full load in the 55ish minutes
![image](https://user-images.githubusercontent.com/9310914/80299359-bff05e80-8761-11ea-8399-8d419ff35e35.png)

And unfortunately, that was it. I started going negative again.
![image](https://user-images.githubusercontent.com/9310914/80299459-853af600-8762-11ea-9168-874db874c58e.png)

So, I said, hell, let me see what happens now with the 5/0 that I had before....
And we'll wait another 56mins for that :)

**Comment by Vitae666** [comment]
Well, went negative again. No idea why that's happening. No logs. There were some spare attacks in the meantime.

**Comment by Vitae666** [comment]
Well...soon as I posted, I dis/enabled, and log hell
4/26/2020 3:06:14 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player FA1754066512CB9A
4/26/2020 3:06:18 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player FA1754066512CB9A
4/26/2020 3:06:22 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player FA1754066512CB9A
4/26/2020 3:06:26 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player FA1754066512CB9A

**Comment by Vitae666** [comment]
Here's what I REALLY don't understand...Auto is currently DISABLED.....
4/26/2020 3:10:35 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player FA1754066512CB9A
4/26/2020 3:10:39 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player FA1754066512CB9A
4/26/2020 3:10:43 AM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player FA1754066512CB9A

Raised it back to 10/10. Dis/Enabled. Still doing the logs. I'm out of spare attacks.

**Comment by MatthieuBonne** [comment]
Going negative is ok, the way I changed the code : countdown means "time until next charge spawns", but fights happen at least 15 minutes apart from each other.
Error logs are different though... Hmm. Please try my new version.

**Comment by Vitae666** [comment]
Ah, never saw it go that far down in negatives before. And I thought I saw the change in code to extend the new fights. 
But the new wrinkle is that after 9hrs of sleep, I only did 2 more attacks...
I was on andymorris when I went to bed. And in game I am at full spares...
![image](https://user-images.githubusercontent.com/9310914/80313932-36ba4580-87bc-11ea-9dc8-7b83a3e79f8f.png)


Will get the new version now.

**Comment by Vitae666** [comment]
Just crashed

This exception was originally thrown at this call stack:
	CQFollowerAutoclaimer.PFStuff.sendPVPFight(int)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	CQFollowerAutoclaimer.AutoPvP.sendFight(int)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	CQFollowerAutoclaimer.TaskQueue.queueTimer_Elapsed(object, System.Timers.ElapsedEventArgs)
	System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync.AnonymousMethod__6_1(object)
    ...
    [Call Stack Truncated]

**Comment by Vitae666** [comment]
Same crash info 6hrs ago.

**Comment by Vitae666** [comment]
Ok, so apparently, CQ PVP has an issue where when new seasons start, there's "dead players" all over the rankings. Right now, my 5 above and 4 below can't be fought. I get the "Can't Fight" error when I click them.
Does it mean that the 10 above/below me are also "dead"? Dunno. BUT, I can't go higher than 10 in the input. Tried to see if 100 would get me past this block. It resets to 10 :)

I tried to do a test build with setting the Maximum to 100, but of course, that crapped out and didn't work. All I get is
4/27/2020 2:50:35 PM
	Error InvalidParams Invalid input parameters
4/27/2020 2:50:39 PM
	Error InvalidParams Invalid input parameters
4/27/2020 2:50:43 PM
	Error InvalidParams Invalid input parameters
4/27/2020 2:50:47 PM
	Error InvalidParams Invalid input parameters


> Mk0ng14 
> This happens every new season, and will settle down in maybe a couple of weeks. I think the players you can't fight are abandoned accounts that have had some sort of bit-rot infect their line-ups which causes the error when the system tries to run the battle. Edited to add: it happens at the start of a season because everyone's rating is set back to zero, and the abandoned accounts which usually languish right at the bottom get into the general mix. After the ratings are re-established they sink back down and don't bother anyone until the next time.
>

**Comment by MatthieuBonne** [comment]
You can't raise to 100 (nice try), game won't let you fight so far. ^^
Please try new version.

**Comment by Vitae666** [comment]
Just about to go to bed. I was able to get into work with 50. Haven't had
an issue yet. We'll, had 4 can't fight errors but were for diff players.
Will check when I wake up. No work, so sleeping looooooong time

**Comment by Vitae666** [comment]
Well, working good so far. Nothing filling up logs.
I think we're good. Opening up another issue that's been happening lately tho :(

**Comment by Vitae666** [comment]
Been meaning to mention, I'm still having the odd crash and it always shows it's during a PVP attempt in the logs.
I redid my version with looking for 50 and not 10 and I haven't had an issue in the past 2 days.
I'm still getting a TON of "Can't Fight" msgs and I'm thinking that the crashes might be happening when the possible fights are 0 so it craps out.
Suggestion, added bit of code that's like this:
If (playersBelowCount.Maximum + playersAboveCount.Maximum = CurrentPVPAttempt)
{whatever the hell the code to wait for the next opponent lineup reset is}

Yeah. I know. The real code is nothing like that :)

With the 50 I can, so far, safely get this:

> 5/10/2020 9:11:26 AM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player BF418BF0E89A57EE
> 5/10/2020 11:11:22 AM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 7FAA1CF38BE60482
> 5/10/2020 11:11:28 AM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 84E6C306B12914C7
> 5/10/2020 11:11:34 AM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 998F03CFAA8ED999
> 5/10/2020 11:11:40 AM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 54F087629A7EB61E
> 5/10/2020 11:11:46 AM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 5E2419613AAA09BB
> 5/10/2020 11:11:52 AM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 7069D57D4DC833CD
> 5/10/2020 11:11:58 AM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 72A8DB51A73732B8
> 5/10/2020 1:11:24 PM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 792CB7FE1FE654BC
> 5/10/2020 1:11:30 PM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 7C7466ECAD6C2C41
> 5/10/2020 1:11:36 PM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 7D754F46970BF991
> 5/10/2020 2:11:22 PM
> 	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 84E6C306B12914C7
> 

With 10, I almost never get more than 3 attempts before a crash. Don't know why, since there's really supposed to be 20 attempts 1st. I'm assuming 10 over and then a fall back of for the 10 below if the 10 over aren't fightable.

**Comment by MatthieuBonne** [comment]
Please tell me if 4.7.4 improves the situation.

**Comment by Vitae666** [comment]
Oh, since you updated it to 50, I don't think I've had any PVP crashes at all. 
Closing this for now. If something pops up that looks related, I'll reopen.
