### ISSUE TITLE
AutoDQ error received from calc

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#58]
Not sure where the error is coming from.
It says it's an AutoDQ error that's coming from the Calc, meanwhile it's logged in CQMCErrors, but I'm leaning towards an interaction between CQMC and CQA.
I ran DQ on CQMC on it's own, and it ran fine. Was stuck at 175 and got up to 183.

> 5/4/2020 1:52:05 PM
> AutoDQ error received from calc
> 
> AutoDQ error received from calc
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
> AutoDQ error received from calc
>    at CQMacroCreator.PFStuff.sendDQSolution()
> AutoDQ error received from calc
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
> AutoDQ error received from calc
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> AutoDQ error received from calc
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> AutoDQ error received from calc
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> AutoDQ error received from calc
>    at System.Threading.ThreadHelper.ThreadStart()
> 

Also, as an odd side note: I ran "Run calc now" 3 times because the timer seemed really short (to used to the pop up error boxes I guess). I saw the time stamp go up on CQMCErrors each time, but there was just the 1 error when I opened the file.
Does, whatever the heck is causing the logs to CQMCErrors, overwrite the file?
Only reason I'm asking is cause if there's more errors leading up to this one, then it's not shown.

The code for the logging is in AutoDQ.cs
`                using (StreamWriter sw = new StreamWriter("CQMCErrors.txt"))`
Looking at the other ones they all have 
`                        using (StreamWriter sw = new StreamWriter("ActionLog.txt", true))`
Could be the "true" bit?

Tho, AutoDQ.cs has this one as well, and I've never seen a wipe of ActionLog
`                    using (StreamWriter sw = new StreamWriter("ActionLog.txt"))`

And the only other one that doesn't have "true" is in the AppSettings.cs, but that would be because having multiple setting listings would be BAAAAAAAD LOL

**EDIT:** Forgot to add that after I got to 183 and timed out, I went back to CQA, clicked "Run calc now" and got the error again.
My thought was that there might have been a weird interaction with a Hero, but the Heroes in the DQs were all different.

**EDIT 2:** Just noticed that there was stuff in Action and Error Log. Wasn't 100% sure it was related, so ran dq again

_Action_
> 5/4/2020 3:37:17 PM
> 	Debug DQFailedAttempts = 1
> 5/4/2020 3:37:17 PM
> 	sendDQSolution a : System.Int32[]
> 5/4/2020 3:37:19 PM
> 	sendDQSolution b : PlayFab.PlayFabResult`1[PlayFab.ClientModels.ExecuteCloudScriptResult]
> 
_Error_
> 5/4/2020 3:37:09 PM
> 5/4/2020 3:37:11 PM
> 	Error Cloud Script Error: Send DQ PlayFab.ClientModels.ExecuteCloudScriptResult

Still get empty timestamps for some reason

**Comment by Vitae666** [comment]
Sorry for the length of the video, but needed to show everything that's going on.
CQA decides not to run the DQ's, but CQMC works fine. It seems to stop running after a certain amount of time. From 3 to 10 seconds on "Using Best lineup" and then a solid 29-31 seconds on "Calc is Running"
But I start up CQMC, tell it to run, and it starts and continues. Damned if I know in the video the part where it timed out because that was quick and about the time CQA times out. But it ran fine soon as I clicked it again. 
I killed the CQMC process BTW cause I didn't know how long it would run for.
But that's pretty much what I'm doing now. Letting CQA run until it stops. Then opening CQMC to finish it off.

[http://youtu.be/TUDTtyNVwlU?hd=1](http://youtu.be/TUDTtyNVwlU?hd=1)
[CQMCErrors.txt](https://github.com/MatthieuBonne/CQAutomater/files/4602770/CQMCErrors.txt)
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4602771/ActionLog.txt)

**Comment by MatthieuBonne** [comment]
Hmm... Fixing debug info in next commit...

**Comment by Vitae666** [comment]
Still the same weirdness with DQ causing a crash on CQMC.
Had this rather lengthy set of errors in my ActionLog
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4639563/ActionLog.txt)
Don't know if it matters, but it was against this lineup
Successfully got enemy lineup for DQ122 - F33,E33,E33,yetithepostman:1000,babypyros:1000
CQA just crashed on it. CQMC knocked it off with no problems. I didn't even try to get CQA to run it again. Already know that it won't work.

**Comment by Vitae666** [comment]
Ok, so latest version, clicking Run Calc Now isn't causing a crash in CQMC, but it IS still doing the really short finish like in my video. But then, the crash in CQMC was when a new DQ day was started. Still on the old one. Won't know about a crash until the new day starts in an hour and 30 mins.
Dunno if the ActionLog is diff tho. It's still a load of things in there but is WAY shorter. 1 entry vs the 4 (or 5?) in the other :)
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4640975/ActionLog.txt)

**Comment by Vitae666** [comment]
Good news, no CQMC crash on the new day. 
BUT it stopped at 137. I clicked "Run Calc Now" again about 4mins after it finished running, and it ran to 149 and stopped. Clicking again another 4mins later gained nothing extra. I wasn't trying to gauge it with time. Just happened to be 4 minute delays due to eating dinner and getting the kids to eat theirs.
Bad news is that by running CQMC on it's own afterwards, I got to 199.
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4641190/ActionLog.txt)

**Comment by MatthieuBonne** [comment]
Current commit has a 10s max time per level ; I'll raise to 30 in next commit.

**Comment by Vitae666** [comment]
Not sure what that means.
There's the self-set solve timeout timer and the in between solves timer
that is the time between sending results. Is that the one you mean? Thought
that was 5secs

**Comment by MatthieuBonne** [comment]
AutoDQ.cs line 180, it sets CQMC delay through command line.

**Comment by Vitae666** [comment]
Ok. I'll try a temp build to see if it works.
Unsure how it would help, but you'd know better than me 😁

**Comment by Vitae666** [comment]
Just to be sure... we're NOT talking about the minimum time to run before
the "solution not found" msg right? This is completely separate? Assuming
it's diff since we have that setting in settings.json.

**Comment by Vitae666** [comment]
Ok, assuming you meant changing "quick 10" to "quick 30" then the delay
worked. I'm waiting for the new dq day to make sure it's all good.
But I'm confused. Is this separate from the setting in settings? The
calcTimeLimit setting. Shouldn't it use that? That was the reason I'd asked
about it being integrated when cqa ran cqmc.
Cause running cqmc seperately is taking the full 300 seconds I have it set
for.

**Comment by Vitae666** [comment]
Well....It ran to 101 and then both CQMC and CQA crashed. Couldn't even get VS to open up to do the debug info. Really weird. Here's the logs that populated.
[ExceptionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4647189/ExceptionLog.txt)
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4647190/ActionLog.txt)

**Comment by Vitae666** [comment]
Reopened CQA and it says it got to 119. It showed 101 on that greyed out way it gets when there's a crash. Guess it sent an extra attempt and then crashed.
Ran it again in CQA. Got to 183. Another crash for CQMC :(
[ExceptionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4647246/ExceptionLog.txt)
[CQMCErrors.txt](https://github.com/MatthieuBonne/CQAutomater/files/4647248/CQMCErrors.txt)
Pretty sure these are the exact same errors. Dunno why there's 2 diff files of them.

Tried CQA again. Didn't get any further due to 30 second time out. 
Same CQMCError details (Previous one deleted to have clean file) but no ExceptionLog...?...
[CQMCErrors.txt](https://github.com/MatthieuBonne/CQAutomater/files/4647262/CQMCErrors.txt)
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4647263/ActionLog.txt)

Ran CQMC directly, and also didn't get any further. Tried with my 300 sec setting and -1 and let it run for an hour and 20 mins before I killed it. Guess I can't beat A33,F33,sparks:3000,valor:7000,undine:8000

**Comment by MatthieuBonne** [comment]
I... err... forgot I had created calcTimeLimit xD Will use it next time.
Trying to find errors in CQMC too !

**Comment by Vitae666** [comment]
Bwahahaha!!
Don't blame ya. I keep throwing errors at you. And I feel like I'm the only
one that has them. Or I'm reporting them faster than the others.

**Comment by Vitae666** [comment]
Just noticed that I thought I'd asked something: Does the calcTimeLimit
need to be ADDED or since it's built in, when CQMC opens it'll know?
I'd imagine it would know and use it, but given that it's a command
line/hidden window type thing, I dunno.
Will try a build and see. Right now, I'm to focused on the new event. Thank
god for Autoclickers :)

**Comment by Vitae666** [comment]
Ok. Taking out the time limit worked. I was on Daily 197 and running CQMC on it's own with a 300 second limit, it would time out with the result.
I set Settings.json with 120. Started up my build of CQA. Ran it and in a little over 2:13 it finished. Ran it a few times and I get different times. One was closer to 3mins. Don't know why the variance in time, but could be the old shitty laptop :)
I'm sure you already knew that just taking the time limit out would work, but at least you don't have to wonder "Will this sonovabitch have something wrong this time with it?!" :)

                proc.StartInfo.Arguments = mode == CalcMode.DQ ? "quick" : "quickdung";
and done :grin:

**Comment by MatthieuBonne** [comment]
Please tell me if 4.7.4 improves the situation.

**Comment by Vitae666** [comment]
Still having occasional issues. Today, DQ crashed CQMC 3 times. Ran CQMC on it's own, and it ran perfectly fine :(
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4719834/ActionLog.txt)
[CQMCErrors.txt](https://github.com/MatthieuBonne/CQAutomater/files/4719836/CQMCErrors.txt)
[ExceptionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4719837/ExceptionLog.txt)

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CQMacroCreator
  StackTrace:
   at CQMacroCreator.PFStuff.sendDQSolution()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Vitae666** [comment]
Still crashing. 
[ExceptionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4726267/ExceptionLog.txt)
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4726268/ActionLog.txt)
[CQMCErrors.txt](https://github.com/MatthieuBonne/CQAutomater/files/4726270/CQMCErrors.txt)

[http://youtu.be/A6u0U9Q3sxs?hd=1](http://youtu.be/A6u0U9Q3sxs?hd=1)

I was on 127 for 3 crashes. Then when I started making the video I went to 128 and then 135. And as you can see I was on the "using best lineup" for a lot longer than usual. And CQMC on it's own ran fine.

Still the same info as above:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CQMacroCreator
  StackTrace:
   at CQMacroCreator.PFStuff.sendDQSolution()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by MatthieuBonne** [comment]
Adding failsafes, please update both CQA and CQMC.

**Comment by Vitae666** [comment]
No crash and it went all the way thru to a natural conclusion. Ran CQMC to make sure and didn't go any further. Of course, could just be that my heroes suck and couldn't beat the lvl :)
So, might be all good.
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4734036/ActionLog.txt)
Closing. Will reopen if needed. Betting it won't tho :)

**Comment by Vitae666** [comment]
I think the issue with the stutter stops is back.
DQ ran. Went to 124 and stopped. I saw that the new version was out, and saw Calc, CQMC and CQA all had the new heroes, so I updated figuring that I ran into one of those heroes and it got the "Unknown Hero" error.
Ran CQA's "Run Calc Now" got to lvl 135.
An hour later said "What the hell, lemme click it again."
AAAAAAAAAND....ran up to 141 :-/
Not that this is informative (at least not to me :smiley:  : 
6/10/2020 5:37:54 PM
	Debug DQFailedAttempts = 0
6/10/2020 5:38:06 PM
	Debug DQFailedAttempts = 0
6/10/2020 6:49:47 PM
	Debug DQFailedAttempts = 0
6/10/2020 6:49:59 PM
	Debug DQFailedAttempts = 0

**Comment by MatthieuBonne** [comment]
How fast did it go from 135 to 141 ? In my logs I see some stuff about "rate limit exceeded", maybe we send solutions too fast ?

**Comment by Vitae666** [comment]
Didn't time it, but not to fast.
Timing don't seem to be an issue with CQMC. It should be waiting the
same 5s(ish) interval since CQMC is doing the sending (I'm assuming)


On 6/11/20, Matthieu <notifications@github.com> wrote:
> How fast did it go from 135 to 141 ? In my logs I see some stuff about "rate
> limit exceeded", maybe we send solutions too fast ?
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/MatthieuBonne/CQAutomater/issues/58#issuecomment-642498600


-- 
Life should NOT be a journey to the grave with the intention of
arriving safely in an attractive and well preserved body, but rather
to skid in sideways, chocolate in one hand, martini in the other, body
thoroughly used up, totally worn out and screaming "WOO HOO what a
ride!."

**Comment by Vitae666** [comment]
I do get the 
`Debug DQFailedAttempts = 0`
errors sometimes still.

Haven't figured out why or what's causing it. But haven't had the main issue where CQA would stop and CQMC would be able to progress further.
