### ISSUE TITLE
Possible Hans acution bug

### ISSUE THREAD

**Issue by braveslice** [MatthieuBonne/CQAutomater#59]
Hi!

I have 3 heroes in bidding: Hans, Yeti and Santaclaus. I have won last 5 biddings on yeti (thx!), history reports bidding efforts for Santaclaus too. However no hint is given that Hans is bidded at all, your history data shows that most (if not all) bidds are under max bidding price limit.  This is at least 5 last bidding rounds, but I would guess more rounds than that has passed.

Cheers!

**Comment by Vitae666** [comment]
I've mentioned bidding weirdness like this before in another post.
He's looking into it 😁

**Comment by braveslice** [comment]
I take the issue back because "1505 (braveslice)" won Hans

What it's worth thins different from before: a)I did some manual bidding for Hans first b) only 2 biddings enabled

Cheers!
