### ISSUE TITLE
Added a Save Settings button to the Other tab

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#60]
Always bugged me a bit that when I made a change to the tabs, I'd have to click Save on each of them. So, I wanted to create a "Save All Settings" type of button. Figured out how to do it from the code, and added it. 
This also has my increase from 10 to 50 PVP Opponents. Like I said in another post, oddly, I've had no issues with searching for 50, but 10 just causes crashes.
Of course, can't attach .cs files, so, obviously, just added .txt to them.
If you want to add it to your build, I'd be honored (even if it's just the Save Settings button)
[Form1.cs.txt](https://github.com/MatthieuBonne/CQAutomater/files/4620098/Form1.cs.txt)
[Form1.Designer.cs.txt](https://github.com/MatthieuBonne/CQAutomater/files/4612079/Form1.Designer.cs.txt)

**EDIT:**
Had to make an edit to Form1.cs
It was saving the Settings.json with Startup settings. I guess something gets stored in some memory or something that even after hours later, clicking my Save to Setting button would over write whatever was done and saved seperately.
Basically, I'd done some changes to my AH and clicked Save AH Settings then later clicked MY Save Settings button and it reverted Settings.json to what it was when I'd started up. BUT I **_THINK_** I sorted that out. Tried to recreate the problem, and it didn't happen anymore.

**EDIT 2:**
Nope...Nope I didn't sort it out.
Just realized I didn't do 1 test.
My original test was to change "max bid" click Save AH Settings then click my Save Settings button, and that worked fine. It didn't overwrite with old data. Which for me was a success because before it would just save with the old data.
This time, I changed the "max bid" and clicked my Save Settings button rather than Save AH Settings and it didn't do squat.
I mean, it re-saved the file with the the previous data, but not the new data.
But it seems that making a change and clicking my button doesn't actually save the new data, just re-saves with the old data.
Shit :disappointed:

**Comment by MatthieuBonne** [comment]
Thanks, edited & included in next commit !

**Comment by Vitae666** [comment]
LOL! I hope you fixed it from my f'd up version 1st tho. Cause I never figured out how to get that damned thing to work :)
