### ISSUE TITLE
Figured I'd share my logs

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#63]
Came home to a CQMC crash around 5:30ish. The weird thing is that it crashed twice. Maybe it was a crash when starting DQ and then another crash when DQ hit one of those weird errors. Posting it here in case it's CQA related.
The ExceptionLog says 5:33 and 5:35, but the CQMCErrors says it was just a few mins ago (but since that's when I clicked the Close, like an idiot and not Debug, that's why)
[CQMCErrors.txt](https://github.com/MatthieuBonne/CQAutomater/files/4686534/CQMCErrors.txt) 
[ErrorLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4686535/ErrorLog.txt)
[ExceptionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4686536/ExceptionLog.txt)
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4686531/ActionLog.txt)

**Comment by MatthieuBonne** [comment]
According to the logs, you had a DataUpdateRateExceeded answer from PlayFab. I'll increase sleep times between tries.

**Comment by Vitae666** [comment]
All of a sudden I'm getting this in my ActionLog every 20-30 seconds.
5/28/2020 12:42:55 AM
	Invalid URI: The Uri string is too long.

5/28/2020 2:40:16 AM
	Invalid URI: The Uri string is too long.

Didn't see it before. Wasn't in the previous ActionLog.

And just like that...It's gone...no reason. Just poof

**Comment by Vitae666** [comment]
Crash. Thought it might be PVP related, but then saw the debug details. Tho. it appears I tried to do 1,115 attacks in 3hrs....
[ErrorLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4696456/ErrorLog.txt)
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4696459/ActionLog.txt)

```
[System.Exception
  HResult=0x80131500
  Message=Must be logged in to call this method
  Source=CQ Auto-follower-claimer-inator
  StackTrace:
   at PlayFab.PlayFabClientAPI.<ExecuteCloudScriptAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.PFStuff.<sendSJClaim>d__101.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoEvent.<EventTimer_Elapsed>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]]([url](url))
```

**Comment by Vitae666** [comment]
Had the same weird thing with PVP. Noticed my PVP timer was in the negatives. I unchecked/rechecked Enable Auto-PVP and it attacked and reset the timer. But it keeps trying to do the attack on who ever CCAE91057CC3A3E2 is. 
It's added to the logs even tho I don't have any spare attacks. I'm guessing it's trying to attack?
[ErrorLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4709995/ErrorLog.txt)

EDIT: Just crashed with the PVP timer in the negatives by just 2 minutes. The previous one was about 14 minutes, but it didn't crash. Guessing it had an issue getting the leaderboard since I attacked the last player they were spamming.
No logs (just the ErrorLog with more of the same attacks) and just the below.
```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=CQ Auto-follower-claimer-inator
  StackTrace:
   at CQFollowerAutoclaimer.PFStuff.<getLeaderboard>d__79.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoPvP.<pickOpponent>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoPvP.<PVPTimer_Elapsed>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]
```

**Comment by Vitae666** [comment]
The shown attack was one that 0'd out my attacks. Haven't attacked since.

[ErrorLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4713795/ErrorLog.txt)
![image](https://user-images.githubusercontent.com/9310914/83462399-217aab80-a439-11ea-9dbb-6b04a7e4c232.png)

**Comment by Vitae666** [comment]
Wokeup to a ton of 
6/2/2020 8:02:10 AM
	Error in PFStuff
	The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4718181/ActionLog.txt)

Tho, it stopped about an hour before I woke up. So, coulda been CQ side and it was fixed.

**Comment by MatthieuBonne** [comment]
Ingame bug, fixed by Gaia now.
About PvP : noted, will look at it asap (ugly busy days irl).

**Comment by Vitae666** [comment]
No worries. 😁

**Comment by Vitae666** [comment]
Ok. Dunno if the recent build addressed PVP or not. Didn't really look.
BUT started it today at 3PM, it's now 1:30AM and it hasn't crashed once. Timer is running perfect. There's nothing in the logs with that multiple target stuff, so I dunno if you took that out, or if it's not needed cause it's running good.

**Comment by Vitae666** [comment]
Started with the URI issue again. Dunno what that's about. It happened about 9 days ago, which I'm guessing makes it an issue with the `Flash: Active today, sending history` bit.
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4739376/ActionLog.txt)

**Comment by Vitae666** [comment]
Another 9 days, another URI issue. Well, 100% sure it's something to do with sending PVP history stuff at this point.

**Comment by Vitae666** [comment]
Honestly, don't know if these are due to PVP Send or the PM that I got from Kong saying they were going to do some maintenance. Or both. Because ErrorLog does have a "pved" bit, but then other errors that I think it was just trying to write to ActionLog at the same time ErrorLog was or something. 

[ErrorLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4822755/ErrorLog.txt)
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4822756/ActionLog.txt)

**EDIT:** For all I know, it's failed attempts at joining the Tourneys. It's 10PM EST and haven't entered any of the Tourneys yet. Dunno.
Also, I should mention that it appears everything else is working fine. I'm not behind on PVP. As for WB attacks, won't know until the current one is dead and a new one avail.

**Comment by Vitae666** [comment]
Ok, finally joined a Tourney. Only the one so far.

> 6/23/2020 11:48:07 PM
> 	Error Sending Flash lineup [29,-14,-71,-165,-66,70,49,-153,59,-52,-214,29,-68,59,80,0,-46,-144] --- {"id":3580,"hero":[0,0,0,0,0,0,0,0,0,0,0,0,96,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,47,0,0,0,0,0,62,0,0,0,0,0,0,0,0,0,0,0,0,0,83,0,37,0,0,35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,71,0,0,0,0,0,0,0,0,60,0,0,0,0,0,0,0,0,0,0,0,68,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,77,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"followers":48585176,"joined":false,"players":27,"promo":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}
> 

Don't know why it says Error, when it worked tho.

And finally something different than all the other errors.

```
6/24/2020 12:49:29 AM
	Error updateFlashHistory  One or more errors occurred. ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at CQFollowerAutoclaimer.PFStuff.updateFlashHistory(JToken json)
```

Unfortunately, nothing new in ActionLog.

**Comment by MatthieuBonne** [comment]
Was afk for a few days, of course my server had some issues at the same time so everything was laggy ; I could only join 5 flashes myself...
It should work better now, sorry. And don't worry with the "error", that's just debug to help me spot issues (all your error messages in ErrorLog are now also sent to my server).

**Comment by Vitae666** [comment]
Ahh..didn't know that errors were sent to you. Nice 😁

**Comment by Vitae666** [comment]
ActionLog
```
7/2/2020 8:00:37 PM
	StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Pragma: no-cache
  Cache-Control: no-store, must-revalidate, no-cache
  Date: Fri, 03 Jul 2020 00:00:50 GMT
  Set-Cookie: PHPSESSID=ad37uhqie5tdl13pka2i5r24mf; path=/
  Server: Apache/2.4.10
  Server: (Debian)
  Content-Length: 0
  Content-Type: text/html; charset=UTF-8
  Expires: Thu, 19 Nov 1981 08:52:00 GMT
}
```
Every 1 - 4 minutes until current time at the moment

```
7/3/2020 1:01:40 AM
	StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Pragma: no-cache
  Cache-Control: no-store, must-revalidate, no-cache
  Date: Fri, 03 Jul 2020 05:01:54 GMT
  Set-Cookie: PHPSESSID=1rhdsgg5nchul6lsggl5aoji00; path=/
  Server: Apache/2.4.10
  Server: (Debian)
  Content-Length: 0
  Content-Type: text/html; charset=UTF-8
  Expires: Thu, 19 Nov 1981 08:52:00 GMT
}
```

Won't post ErrorLog since you said you get those.

**Comment by Vitae666** [comment]
Still happening:

```
7/11/2020 8:08:58 PM
	StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Pragma: no-cache
  Cache-Control: no-store, must-revalidate, no-cache
  Date: Sun, 12 Jul 2020 00:09:15 GMT
  Set-Cookie: PHPSESSID=f64emglmuki6a89rmoeltkq4pm; path=/
  Server: Apache/2.4.10
  Server: (Debian)
  Content-Length: 0
  Content-Type: text/html; charset=UTF-8
  Expires: Thu, 19 Nov 1981 08:52:00 GMT
}
```

**Comment by Vitae666** [comment]
And still...

```
8/17/2020 4:24:35 PM
	StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Pragma: no-cache
  Cache-Control: no-store, must-revalidate, no-cache
  Date: Mon, 17 Aug 2020 20:24:38 GMT
  Set-Cookie: PHPSESSID=21gegtm846eanrmubmi016hn21; path=/
  Server: Apache/2.4.10
  Server: (Debian)
  Content-Length: 0
  Content-Type: text/html; charset=UTF-8
  Expires: Thu, 19 Nov 1981 08:52:00 GMT
}
```
Tho, the real question is what's with that Expires date?

![image](https://user-images.githubusercontent.com/9310914/90441196-893eab00-e0a6-11ea-8d1c-1a131cd7b3cd.png)

**Comment by Vitae666** [comment]
> Was afk for a few days, of course my server had some issues at the same time so everything was laggy ; I could only join 5 flashes myself...
> It should work better now, sorry. And don't worry with the "error", that's just debug to help me spot issues (all your error messages in ErrorLog are now also sent to my server).

Question then. Are ALL the logs sent to you? There's the ExceptionLog and CQMCErrors that pop up. Obviously ActionLog as well.
Are they sent in realtime or only on "Flash day" when it's "sending History" ? Are they not the actual files, but just from a cache or something?
Asking because usually I delete them after a few days depending on how big they get. Had one that was several MB before. Feel like I asked this one before, but not sure

**Comment by MatthieuBonne** [comment]
Only ErrorLog is sent, in fact it adds a row in a database table each time CQA writes in your log file, and I purge my table every few days. But it's sent all the time.

Sorry about the ActionLog spam, it's in updateFlashHistory, I'll remove it next commit.
