### ISSUE TITLE
CQA System.Exception

### ISSUE THREAD

**Issue by djozz911** [MatthieuBonne/CQAutomater#64]
Hello,
I recently had 2 errors : 

30-05-2020 @ 7:21
Application : CQ Auto-follower-claimer-inator.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.Exception
   à PlayFab.PlayFabClientAPI+<ExecuteCloudScriptAsync>d__13.MoveNext()
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   à System.Runtime.CompilerServices.TaskAwaiter1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   à CQFollowerAutoclaimer.PFStuff+<sendSJClaim>d__101.MoveNext()
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   à System.Runtime.CompilerServices.TaskAwaiter1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   à CQFollowerAutoclaimer.AutoEvent+<EventTimer_Elapsed>d__8.MoveNext()
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

and nothing in the ErrorLor.txt

02-06-2020 @ 14:49
Application : CQ Auto-follower-claimer-inator.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.NullReferenceException
   à CQFollowerAutoclaimer.PFStuff+<sendBid>d__104.MoveNext()
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   à System.Runtime.CompilerServices.TaskAwaiter`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   à CQFollowerAutoclaimer.TaskQueue+<queueTimer_Elapsed>d__3.MoveNext()
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Last entries of ErrorLog.txt : 
02/06/2020 14:48:39
02/06/2020 14:48:44
	Error Cloud Script Error: bid {"ok":false,"err":"Wrong server request"}
02/06/2020 14:48:47
02/06/2020 14:48:51
02/06/2020 14:48:56
	Error Cloud Script Error: bid {"ok":false,"err":"Wrong server request"}
02/06/2020 14:49:02
	Error Cloud Script Error: bid {"ok":false,"err":"Wrong server request"}
02/06/2020 14:49:03
02/06/2020 14:49:09

**Comment by djozz911** [comment]
Another crash this morning (no entry in ErrorLog)  : 

04-06-2020 @ 7:38
Application : CQ Auto-follower-claimer-inator.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.Exception
   à PlayFab.PlayFabClientAPI+<ExecuteCloudScriptAsync>d__13.MoveNext()
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   à System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   à CQFollowerAutoclaimer.PFStuff+<sendSJClaim>d__101.MoveNext()
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   à System.Runtime.CompilerServices.TaskAwaiter`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   à CQFollowerAutoclaimer.AutoEvent+<EventTimer_Elapsed>d__8.MoveNext()
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by MatthieuBonne** [comment]
Tried preventing that in today's commit.

**Comment by djozz911** [comment]
No System.Exception with last week commit. Upgraded today to last version (4.7.5b)
I think I can close this issue.
