### ISSUE TITLE
So much for automating the new events (maybe from now on)

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#65]
[https://www.kongregate.com/forums/910715-cosmos-quest-the-origin/topics/1912539-upcoming-beta-test-g-a-m-e-s-other-event-info](https://www.kongregate.com/forums/910715-cosmos-quest-the-origin/topics/1912539-upcoming-beta-test-g-a-m-e-s-other-event-info)

> Every time you complete an activity, you have a 20% chance to return injured. Returning injured simply prevents you from performing another activity until you have healed your wound.
> Healing your wound requires **solving a captcha** to perform. This is the intended method of preventing automation.
> Side note - **Purchasing an upgrade will also trigger the captcha** - you won't be able to automate upgrade purchases whilst offline

**Comment by MatthieuBonne** [comment]
Yeah I know. Well, I don't *want* to automate events, it's just that I want even less to lose sleep time. So if their new events aren't SJ-like, it's all good.

**Comment by Vitae666** [comment]
Seems like GAME is going to be one of those "sleepless ones" and that FUCKING captcha....ugh

**Comment by MatthieuBonne** [comment]
If you come up with a decent strategy in which CQA can help (with captcha-less actions), please tell me...

**Comment by Vitae666** [comment]
Wish I knew.
Crazy thing was when I suddenly saw lines in the captcha and thought
someone was able to beat them.

**Comment by Vitae666** [comment]
![image](https://user-images.githubusercontent.com/9310914/86068977-a19b2d80-ba46-11ea-92f2-6da64b4d2b1f.png)

**Comment by Vitae666** [comment]
Might as well close since you'd put
No _**public**_ captcha solver
