### ISSUE TITLE
Rerolling Snake event?

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#66]
Is there a way to? I mean, if you get a shit roll, is there a way to have it try again or are you stuck with it? Thought unchecking Snake and/or Enable Auto-Events might kick it, but no luck.
Even tried my own build with a slightly higher lower roll and it never tried again. Even tho my lower (75) was more than the current min (69).
Doesn't seem to want to roll again.

**Comment by MatthieuBonne** [comment]
Try PFstuff.cs:230 (...CCDone < 200). Don't go over 300-315 though.

**Comment by Vitae666** [comment]
Ahhh...I got ya. Thought un/rechecking would do another reroll. Kinda
like how un/rechecking Enable Bidding in AH resets the timer to
00:00:59 ;-)
No worries I won't.

On 6/11/20, Matthieu <notifications@github.com> wrote:
> Try PFstuff.cs:230 (...CCDone < 200). Don't go over 300-315 though.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MatthieuBonne/CQAutomater/issues/66#issuecomment-642500295


-- 
Life should NOT be a journey to the grave with the intention of
arriving safely in an attractive and well preserved body, but rather
to skid in sideways, chocolate in one hand, martini in the other, body
thoroughly used up, totally worn out and screaming "WOO HOO what a
ride!."
