### ISSUE TITLE
ILTemplate.cs & Common.cs ?

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#67]
[ActionLog.txt](https://github.com/MatthieuBonne/CQAutomater/files/4769199/ActionLog.txt)
Have a bunch of `Object reference not set to an instance of an object.` in the ActionLog. 
Decided to see what that might mean from Google.
One suggestion was to do a step thru debug, so I started doing it.
At one point (rather quickly into it, so I'm doubting that this the reason for the error, it asked me to find `ILTemplate.cs` and there is none.
The only place ILTemplate.cs is mentioned is in `CQ Auto-follower-claimer-inator.pdb` with a direct line to my own computer, so I don't even know where it's being generated from.
`C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\obj\Debug\ILTemplate.cs`
But the file's not there.

Google also pointed me to
[https://github.com/Fody/Costura/blob/master/Costura.Template/ILTemplate.cs](https://github.com/Fody/Costura/blob/master/Costura.Template/ILTemplate.cs)
Damned if I know what that file means/does. BUT I get it from that link anyways.
I continue on, and seconds later it wants Common.cs which, no shock is also on that github. I get that as well.
About 3 minutes into pressing and pretty much holding down the F11 key, I realize, I don't even know WTF I am looking for. No idea if a box will pop up saying `Object reference not set to an instance of an object.` or what. Coulda been a time of day/Event/Shitty Internet/Shitty CQ side error. Damned if I know.
BUT either way, figured I'd mention at the least that there's 2 files that are somehow being mentioned but not existing. I couldn't even go further with the steps unless I had those files.
Oh and Common.cs is also mentioned in `CQ Auto-follower-claimer-inator.pdb` as well as a file called `.suo`

```
Locating source for 'C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\obj\Debug\ILTemplate.cs'. (No checksum.)
The file 'C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\obj\Debug\ILTemplate.cs' does not exist.
Looking in script documents for 'C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\obj\Debug\ILTemplate.cs'...
Looking in the projects for 'C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\obj\Debug\ILTemplate.cs'.
The file was not found in a project.
The debugger will ask the user to find the file: C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\obj\Debug\ILTemplate.cs.
The user pressed Cancel in the Find Source dialog. The debug source files settings for the active solution have been modified so that the debugger will not ask the user to find the file: C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\obj\Debug\ILTemplate.cs.
The debugger could not locate the source file 'C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\obj\Debug\ILTemplate.cs'.
```

**Comment by MatthieuBonne** [comment]
I don't think it's related, but could you please tell me when that happens ? While in AutoEvents, PvP, DQ...?

**Comment by Vitae666** [comment]
Hasn't happened again since the last.
Going by the log, it started 9 mins before DQ went in motion. But then
stopped.
Did it again nearly an hour after and almost an hour each time.
And then twice during MC, but almost an hour later. And a few more times
later, also with about an hours diff.
It COULD be PVP. But with no PVP log being generated, can't be certain. And
even then, it could be circumstantial.
