### ISSUE TITLE
AH Wonkiness

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#72]
CQA AH put a bid in WAY before it was time....
It bid almost 4hrs ago. (Time now: 6:48 PM)
6/29/2020 2:51:57 PM	Bid on hero Spike for: 11794UM.

![image](https://user-images.githubusercontent.com/9310914/86063348-afe24d00-ba38-11ea-85a5-ae05d008c518.png)

**Comment by MatthieuBonne** [comment]
Haven't you checked "bid immediately..." ?

**Comment by Vitae666** [comment]
I just looked, and while I'm 99.9% sure I never had it checked off before, it was now. I just downloaded and started up 4.8.1 so I can't tell if it was enabled automatically or not. But I've never had AH do any bids until it was down to the wire.
See the Issue I just submitted in case you're wondering why I think it could have been a 4.8.1 thing.

EDIT: Ugh. Ok, restored a previous version of Settings, and yeap, instantMaxPriceBid was set to true. I'll be damned if I **_ever_** saw it place a bid before it was down to 10 seconds tho. Weird.
So, UNCHECKING that will do what? Not bid at all, or do what I thought it was doing all this time and bid at the last second?
I just don't want to be bidding and being the REASON that the bid is higher with hours left to go :)

**Comment by MatthieuBonne** [comment]
Checking it says "if my bid is 300 and the current bid is the last one I'll be able to set, do it asap". Honestly it's only useful if there are server issues that cut auction length (remember when some lucky ones won lep for less than 1k because server crashed during hours and noone could outbid).

**Comment by Vitae666** [comment]
Ok, think I got what you mean.
Still tho, how would it work without it checked? Work the way that I was thinking it was? 10 seconds (or whatever) before the end, place a bid if I can afford it?
Asking just because I feel like if I'd waited on that bid, I could have creeped up at the last second and caught a bidder napping.
Yeah, I know, maybe not, but hell, I can dream :)

**Comment by MatthieuBonne** [comment]
> Work the way that I was thinking it was?

Yep.
