### ISSUE TITLE
WB error

### ISSUE THREAD

**Issue by LudoKressh** [MatthieuBonne/CQAutomater#76]
I've had this issue since the last game update :

> 11/09/2020 05:09:55
> 	Error Cloud Script Error: send WB {"ok":false,"err":"A new WB has spawned, please refresh"}

There is no more automated attack

**Comment by Vitae666** [comment]
I got this every minute or so

9/10/2020 10:00:09 AM
	DOYENNE No Heroes fought with: A35 A35 A35 A33 A33 A33

Then

9/10/2020 10:39:49 AM
	DOYENNE No Heroes fought with: A35 A35 A35 A33 A33 A33
9/10/2020 10:41:14 AM
	SUPER DOYENNE No Heroes fought with: A35 A35 A35 A33 A33 A33

Until

9/10/2020 11:56:48 AM
	SUPER DOYENNE No Heroes fought with: A35 A35 A35 A33 A33 A33

But the last time I got Ludo's error was a while ago

9/10/2020 11:56:49 AM
	Error Cloud Script Error: send WB {"ok":false,"err":"A new WB has spawned, please refresh"}
9/10/2020 11:57:20 AM
	Error getWebsiteData  http failed, retrying --- The operation has timed out
9/10/2020 11:57:21 AM
	Error AutoWB Catched error Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall.
9/10/2020 11:57:23 AM
	Error getWebsiteData  The operation has timed out ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)

And I'm getting these now for a long time now

9/11/2020 2:37:02 AM
	Error getWebsiteData  http failed, retrying --- The operation has timed out
9/11/2020 2:37:04 AM
	Error getWebsiteData  The operation has timed out ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
9/11/2020 2:37:44 AM
	Error getWebsiteData  http failed, retrying --- The operation has timed out
9/11/2020 2:37:47 AM
	Error getWebsiteData  The operation has timed out ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)


EDIT:
And no mention of MOAK in those "fought with" logs at all, but might be what the Error's are about :)

![image](https://user-images.githubusercontent.com/9310914/92876729-6f0f9880-f3d8-11ea-8d7b-2e40230c0271.png)


EDIT 2:
Reloaded CQA but it didn't help. But at least it's _trying_ to attack MOAK now...

9/11/2020 2:57:53 AM
	Error Cloud Script Error: send WB {"ok":false,"err":"A new WB has spawned, please refresh"}
9/11/2020 2:59:21 AM
9/11/2020 2:59:21 AM
	Error Cloud Script Error: send WB {"ok":false,"err":"A new WB has spawned, please refresh"}

9/11/2020 2:56:29 AM
	MOTHER OF ALL KODAMAS Heroes Allowed fought with: emily:99 dullahan:99 aathos:81 athert:99 ageum:99 aurora:99
9/11/2020 2:57:53 AM
	MOTHER OF ALL KODAMAS Heroes Allowed fought with: emily:99 dullahan:99 aathos:81 athert:99 ageum:99 aurora:99
9/11/2020 2:59:21 AM
	MOTHER OF ALL KODAMAS Heroes Allowed fought with: emily:99 dullahan:99 aathos:81 athert:99 ageum:99 aurora:99

**Comment by djozz911** [comment]
I have the same errors too, using CQA 4.8.2b

**Comment by Cirkulis** [comment]
Same here, v4.8.2b, my error log is now 20 MB and I'm running out of disk space... Please fix Auto-kun :(
https://pastebin.com/meRyNcAJ

**Comment by MatthieuBonne** [comment]
Fixed in the coming exe
