### ISSUE TITLE
4 Requests and a Question

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#9]
1) I'd asked about this back when Wiedmolol was the creator, but might as well ask again: 
Is it Possible to add Chest rolls to the ActionsLog?
It logs the leveling of heroes, would be nice to see the Chest results there. In case you decide to run 100 Hero chest rolls just to come back to it crashed for some reason and no idea what got rolled.

2) For the hero selectors in Auction House and Level, is there anyway that they can be sorted alphabetically? It's sorted in DQ, PvP and WB so I'd imagine it should be possible.

3) Is there a way to add something that would automatically buy Buildings? Select if you want to buy 1/10/25/100/Max/NXT/MXT, or just use whatever you already have set in game (might be easier to use what's in game) and when a building becomes buyable, it buys it.

4) Can we get the Dungeons to start solving automatically like the Daily Quests do?

And Question: I know back in the day when Wiedmolol was the sole coder, there was no way to do things like the Daily Events or even Experiments. Has that changed at all with the advancement of code? Like randomly choosing which 3 Follower selections to do. Or clicking either Left or Right on Keys. Or randomly clicking on the Match game. Stuff like that.
I'm going to assume the answer to that is "No. It's still no possible" but I might as well ask.

**Comment by MatthieuBonne** [comment]
Hi !
1. It is possible, good idea, I'll do it soon.
2. Same ! :)
3. That's quite different, it's not PvP-related. In theory it can be done of course, but for now all the automater work goes through PlayFab, we don't touch the kong-based idle game. So, we *could* implement that, but that's some bit of work, and I don't plan to do it. Same with experiments.
4. It's related to your last question : yes, we can include events in the automater, and well, tournaments too (afaik some private-calc users coded that). We could even plug lucky followers to the public gdoc, both to find best solutions and to fill the sheet with new data : that's what I intend to do next. But again, each event means coding time, I'm no C# expert and I have a job too, so I can't promise any ETA. Any help is welcome. :)

**Comment by Vitae666** [comment]
Thanks. 
Thought since when dungeon time happens and the automater knows and can, with a button click, do it, it could automate that as well.
And I know squat about coding. I can look at it and kinda rig something up based on it, but doing new type stuff is beyond me.

**Comment by MatthieuBonne** [comment]
Just sent a commit addressing points 1 & 2, please send your feedback. :) Thinking about events next...

**Comment by Vitae666** [comment]
1 more request?
Ya know how in the Level tab when you can't level a hero anymore because they reached max and you get a pop-up window alerting you? 2 words: Auction House :)

**Comment by MatthieuBonne** [comment]
What do you mean ? Adding the same popup in AH tab ?

**Comment by Vitae666** [comment]
Yeap. Some how I'd won an auction on one of those 33 lvl per auction heroes 3 times and didnt know it. Only found out because of the MacroCreator.
So, a pop-up like how you try to level a maxed hero, one that says you can't bid cause of max. Maybe an uncheck of the box as well, but I'm thinking that wouldn't be possible cause it's userside.

**Comment by Vitae666** [comment]
Wasn't sure if this was added or going to be added or "Nope!"

**Comment by MatthieuBonne** [comment]
It's a "todo" ! :)

**Comment by Vitae666** [comment]
In the meantime, any chance of a display in AH that shows the current level of the Hero?
Enable bidding on:
{HeroName} up to level {MaxLVL} max price {MaxBidAmount} Current {CurrentLVL}
Same could be handy in the Level tab so keep track of how many more levels you need to get to 99. Maybe with added cost left as a thought?
Again, don't know if it's possible in either of those, but I think they would be welcomed.

(Don't hate me for the suggestions ;-) )

**Comment by Vitae666** [comment]
OH! And have your current UM and PG/CC/AS appear on their proper tabs/areas....
NOW you can hate me ;)

**Comment by MatthieuBonne** [comment]
"In the meantime, any chance of a display in AH that shows the current level of the Hero?" -> granted and done :)
Level requires more work, I'll do it later.
Where should be display currencies ? Bottom of level tab ?

**Comment by Vitae666** [comment]
By current level of the hero I of course mean the hero you own. If you own.

The currencies I'd say next to the area that they are used? Not home right now so can't even remember the display.
But like the checkbox then the currency being used then the current on hand.
Something like that? 
Unless it causes a lot of moving and changing of things. Then at the top of the level tab is kewl too.

**Comment by MatthieuBonne** [comment]
Done !

**Comment by Vitae666** [comment]
Any update on adding the Current Hero Level on the Level tab? 
I know you said it would take more work, but thought I'd check in like the annoying bastard I am ;-)

CQA obviously knows right now that my Raider Rose is lvl 99 as soon as I start it up because I get the pop up and I don't have enough AS on hand to buy another level.

**Comment by MatthieuBonne** [comment]
Done in next commit.
